- brkt_cli/__init__.py
- setup.py
Added ca_cert file to be distributed with python package and
read file from the relative package location.
Testing done:
- Tested encryption from root of repo
- Tested in virtualenv with python setup.py install and ran
script
> Distribute ca_cert.pem with setup.py

- brkt_cli/__init__.py
- test.py
Truncate the AMI description, so that it doesn't exceed 255 characters.
Convert _get_encrypted_image_name() to a new _append_suffix() function
that's called when generating both the AMI name and suffix.
Remove brittle tests that make assumptions about the format of the AMI
name suffix.
Change-Id: I64b63236bc6f6cd30c8ceac8000386bbf78e0039
> Truncate AMI description to 255 characters

- brkt_cli/__init__.py
- brkt_cli/service.py
- iam.json
- test.py
When image encryption fails, point the user to the instance console log.
Write the console log to a temporary file, if possible.
Change-Id: I0a573506e96cc323f4d67cf14bc7246776f5d418
> Image encryptor fails without sufficient details

- brkt_cli/__init__.py
- brkt_cli/service.py
- test.py
Retry all AWS API calls that operate on resources that were created by
brkt-cli.  Add a @retry_boto decorator that calls the wrapped function
with up to 5 retries until the call succeeds.
Change-Id: Ib4112186505a8ad669a56bf1466e1b81e23d8665
> Retry all AWS operations

- brkt_cli/__init__.py
- test.py
If an instance fails to launch, it can go directly into a terminated
state.  Raise an InstanceError when this happens, unless the caller is
explicitly waiting for the 'terminated' state.
Change-Id: Ifed93808f7674e07e49ee2bc31faf3dacb0e6031
> Handle terminated state when waiting for an instance

- brkt_cli/__init__.py
Make EncryptionError a subclass of BracketError, so that we don't log a
traceback unless the user specifies -v.
Change-Id: I0bc4b35b7520a19d2b8bf0d22c425f317fec79ca
> Make EncryptionError a subclass of BracketError

- brkt_cli/__init__.py
Catch KeyboardInterrupt.  Only log the traceback if -v was specified.
Change-Id: Ice68d0054b83381496bddf8557c5e837e1d896e3
> Don't log a traceback on keyboard interrupt

- brkt_cli/__init__.py
- test.py
Add an --encrypted-ami-name option.  When the name is specified, pass it
through to the register_image() call.  Break out the maximum name length
into a constant.
Change-Id: I3cf20075137552ecdeb3edc12ab5d599386e7795
> Allow specifying the encrypted AMI name as a command option

- brkt_cli/__init__.py
- brkt_cli/service.py
- test.py
When --encrypted-ami-name is specified, verify that the name follows the
EC2 image naming rules.
Change-Id: I10ab6d6c864411ae284ae7579dab5cc8a19f3b97
> Validate AMI name

- brkt_cli/__init__.py
Tell the user that we couldn't contact the encryptor instance, instead
of just logging the IP address.
Change-Id: I9df055cb941392fcb0986d67835152b96829da44
> Vague error when encryptor does not come up

- brkt_cli/__init__.py
- brkt_cli/service.py
Make --key a hidden option.  It's no longer required to launch the
encryptor node, and is only used for development.
Change-Id: I834c9c1d4a8be0547820acb4177514f9902faa30
> Don't require key pair name

- brkt_cli/encrypt_ami_args.py
The refactoring work in commit 72eaa85ebe15d3953f697476a592d9b0d94d5662
reverted the recent change to the --key argument and made it a required
argument.  Make --key a hidden, optional argument again.
Also make --encryptor-ami a hidden argument, since it's only used
for development.
> Make the --key and --encryptor-ami arguments hidden and optional

- brkt_cli/encrypt_ami.py
- brkt_cli/service.py
- test.py
Handle the server returning an "unsupported_guest" failure code.  Sample
output:
...
14:38:11 Waiting for encryption service on i-82ebd859 at
52.27.165.218
14:38:50 Creating encrypted root drive.
14:39:00 Terminating encryptor instance i-82ebd859
14:39:00 Waiting for instances to terminate.
14:39:57 Deleting orphaned volume vol-1b32e2fd
14:39:58 Deleting orphaned volume vol-1832e2fe
14:39:58 Deleting orphaned volume vol-f333e315
14:39:58 Deleting orphaned volume vol-8833e36e
14:39:58 Deleting temporary security group sg-8fccb9eb
14:39:58 Deleting snapshot copy of original root volume snap-
ec370fae
14:39:58 The specified AMI uses an unsupported operating system
> Handle unsupported guest failure code

- brkt_cli/encrypt_ami.py
- brkt_cli/util.py
- test.py
Remove the encryption time estimate and log only percent done.  Turned
out that AWS disk I/O is not reliable enough to allow us to calculate a
realistic time estimate.
> Remove encryption time estimate

- brkt_cli/service.py
The AWS API can occasionally return an empty result set instead of an
API error.  Detect this case and raise an EC2ResponseError, to avoid a
"list index out of range" exception.
> Handle empty AWS API responses

- reference_templates/README.md
- reference_templates/vpc-dual-az-with-nat.json
- reference_templates/vpc-dual-az-with-nat.py
The brkt HSMProxy and API are now accessed via ports
7001 and 7002 respectively. This commit updates the
reference VPC to enable egress on ports 7001 and
7002
> Updates reference VPC to include egress on 7001/2

- brkt_cli/__init__.py
- brkt_cli/aws_service.py
- brkt_cli/encrypt_ami.py
- brkt_cli/encrypt_ami_args.py
- brkt_cli/encryptor_service.py
- test.py
Split the service module into encryptor_service and aws_service, so that
it doesn't become a dumping ground.  This is in preparation for adding
another module that talks to the Bracket service.
Test plan: Ran unit tests, encrypted an AMI.
> Refactor services

- brkt_cli/encrypt_ami.py
Commit 72eaa85ebe15d3953f697476a592d9b0d94d5662 unintentionally caused
brkt-cli to get the encryptor AMI list from stage instead of prod.
Reinstate the intended behavior and get the AMI list from prod by
default.
> Get encryptor AMI list from prod by default

- .travis.yml
- brkt_cli/__init__.py
- brkt_cli/bracket_service.py
- setup.py
Add the following options at the top level of the brkt command:
--username (required)
--password (optional)
--api-root (hidden, development only)
--no-verify-cert (hidden, development only)
brkt-cli now authenticates with the Bracket service before doing
any work.
If --password is not specified, prompt the user for the password.
If the EULA has not been signed, prompt the user with the link to the
EULA text.  The user must type the word "YES" (case-insensitive) in
order to accept the EULA.
Add a new BracketService class for code that talks to the Bracket
service API.
> Check and accept EULA in brkt-cli

- brkt_cli/aws_service.py
- brkt_cli/encrypt_ami.py
If something unexpected happens during cleanup, log the traceback, so
that we know where the problem occurred.  Move the bulk of the cleanup
code into its own function, to avoid a massive finally block inside the
encrypt() function.
When deleting a volume, ignore InvalidVolume.NotFound.  This can happen
when AWS deletes a volume that was attached to a terminated instance,
and we then attempt to delete the volume explicitly.
Remove extra log message that was printed when encryption completes.
> Improve error handling during cleanup

- README.md
- brkt_cli/__init__.py
- brkt_cli/aws_service.py
- brkt_cli/encrypt_ami.py
- brkt_cli/update_encrypted_ami.py
- brkt_cli/update_encrypted_ami_args.py
- brkt_cli/util.py
- test.py
This change adds the update-encrypted-ami option to the
brkt_cli. It allows a user to retrieve a metavisor
upgrader AMI and use it to upgrade an already encrypted
AMI. This provides a speed improvement for users who
wish to update their encrypted AMIs.
The user must specify the metavisor updater AMI as an
argument. This requirement will be taken away in a
near-future commit.
> Update encrypted ami

- brkt_cli/__init__.py
- brkt_cli/aws_service.py
- brkt_cli/encrypt_ami.py
- brkt_cli/encrypt_ami_args.py
- brkt_cli/update_encrypted_ami.py
- test.py
Add --subnet and --security-group options to the encrypt-ami subcommand.
The subnet is used when running both the snapshotter and encryptor
instances.  The security groups are used when running the encryptor
instance.
Clean up the command line parsing code to check the subparser name
instead of referencing argv[0].  The old code broke when passing -v to
the brkt top-level command.
> Specify subnet and security group for image encryption

- brkt_cli/__init__.py
- brkt_cli/aws_service.py
- brkt_cli/encrypt_ami.py
- brkt_cli/update_encrypted_ami.py
- test.py
When a subnet is specified but security groups are not, create the
temporary security group in the VPC of the given subnet.  When both are
specified, make sure that they are in the same VPC.
Change the return type of create_security_group(), so that it returns an
object instead of an id.  This is consistent with the other create_xxx()
methods in AWSService.
Remove log level cruft from command_encrypt_ami().  We initialize
logging in main().
> Create temporary security group in the same VPC as the subnet

- brkt_cli/__init__.py
- brkt_cli/aws_service.py
- brkt_cli/encrypt_ami.py
- brkt_cli/encryptor_service.py
- test.py
- aws_service instance launch now takes user-data and instance profile
name args.
- change inputs to register_new_ami()
- accept a new 'insufficient_permissions' failure code from the encryptor
- remove requests dependency (replaced with urllib2)
- rename some encrypt_ami functions to public (no underscore)
> Refactor brkt_cli library to enable extension.

- brkt_cli/__init__.py
- brkt_cli/aws_service.py
- brkt_cli/encrypt_ami.py
- brkt_cli/encrypt_ami_args.py
- brkt_cli/update_encrypted_ami.py
- brkt_cli/update_encrypted_ami_args.py
- test.py
Currently metavisors determine what yeti to
contact by reading an s3 bucket. The brkt-env
option will tell the encryptor what address to
write into the metavisor image.
Testing: launched encryptor instance and verified
userdata was set properly.
> Adds brkt-env option

- brkt_cli/encrypt_ami.py
The S3 encryptor version modifies the instance bdm post launch.
Once the encryptor instance is done running, update its local attributes
before reading them.
> Fetch latest encryptor_instance data before use

- brkt_cli/encrypt_ami.py
- brkt_cli/encrypt_ami_args.py
- brkt_cli/update_encrypted_ami_args.py
- test.py
Brkt-env now defaults to an empty string
instead of 'prod'. The MV will use s3 if
an empty string is passed.
> Remove default for brkt-env option

- brkt_cli/encrypt_ami.py
The prior patch was slightly broken in that it only put one of the
keys into the resultant dict.
> Fixup handling of api endpoint overrides

- README.md
- brkt_cli/update_encrypted_ami_args.py
Use "ID" instead of AMI_ID, UPDATER_AMI_ID to be consistent with the
usage of encrypt-ami.
> Update update-encrypted-ami usage

- brkt_cli/encrypt_ami.py
- test.py
Run the guest instance with instance type m3.medium, to avoid cost and
startup time overhead.  Log the virtualization type at debug level,
since it's not a status update.
> Make guest instance type m3.medium

- brkt_cli/__init__.py
- brkt_cli/encrypt_ami.py
- brkt_cli/update_ami.py
- brkt_cli/update_encrypted_ami_args.py
- test.py
Add --subnet and --security-group options to the update-encrypted-ami
command.
Add a unit test for update_ami(). Update the application logic to always
call aws_svc instead of the .update() method on the object, so that
things work as expected for both production and unit tests.
Returns the new AMI id from update_ami(), and prints it to stdout, like
we do with encrypt().
> Support subnet and security groups when updating an encrypted AMI

- brkt_cli/aws_service.py
The DeleteSecurityGroup API can return either InvalidGroup.InUse or
DependencyViolation error. Handle both error codes. Remove
max_retries=20, so that the call doesn't hang for 72 hours if the API
keeps returning the error.
> Handle DependencyViolation when deleting security group

- brkt_cli/encrypt_ami.py
Otherwise the block device mapping shows up as {} and we get a key
error with '/dev/xvda' when snapshotting the root volume
> Make sure we refresh instance state after waitng for instance to stop

- brkt_cli/__init__.py
- brkt_cli/aws_service.py
- brkt_cli/encrypt_ami_args.py
- brkt_cli/update_encrypted_ami_args.py
- reference_templates/brkt-cli-iam-permissions.json
- test.py
When the subnet isn't specified, make sure that the specified security
groups are in the default VPC.  Add a get_default_vpc() method to
AWSService.
Replace the --validate-ami and --no-validate-ami options with a new
--no-validate option that controls validation of AMIs, subnets, and
security groups.  Hide the old options for the short term so that we
don't break backward compatibility.
Add support for a default VPC to the test framework.  Create test
security groups in that VPC when the VPC id is not specified.
> Improve security group validation, add --no-validate option

- brkt_cli/__init__.py
- brkt_cli/encrypt_ami_args.py
- brkt_cli/update_encrypted_ami_args.py
Get the encryptor AMI from the service during update-encrypted-ami.
Remove the --updater-ami option and add a hidden --encryptor-ami option
for development.  Remove the extra call to validate_encryptor_ami().
The validation is already being done inside _connect_and_validate().
> Get encryptor AMI automatically during update

- brkt_cli/encrypt_ami.py
If the guest AMI's root disk is attached at at different
attach-point, then treat as legacy mode which will use
the metavisor instance to create the AMI instead of the guest
instance. However, for such AMIs, the guest license information
will be lost.
Testing.
Works for Centos 7.1 AMI ami-7bc3f94b which attaches root disk
at /dev/sda.
> Metavisor requires the root disk to be attached at "/dev/sda1".

- brkt_cli/__init__.py
- brkt_cli/encrypt_ami_args.py
- brkt_cli/update_encrypted_ami_args.py
Remove options that were deprecated in 0.9.10.
> Remove --validate-ami and --no-validate-ami options

- brkt_cli/__init__.py
- brkt_cli/aws_service.py
- brkt_cli/encrypt_ami.py
- brkt_cli/update_ami.py
- test.py
When checking the guest AMI, fail validation if we find tags that were
created during image encryption.
Refactor the validation code, so that it's more testable.  Move
validation logic out of AWSService and into brkt_cli.  This thins out
the AWSService implementation, and ensures that the validation logic
gets unit tested.
Add switchable retry logic to AWSService.get_image(), so that we don't
retry the operation for AMIs specified on the command line.  These AMIs
were created long enough ago that retry is not necessary.
> Don't attempt to encrypt an already encrypted image

- brkt_cli/__init__.py
- setup.py
Checking inside main() was too late in the process.  Setup would fail on
Python 2.6 because it couldn't load version 2.7.0 of the requests
library.
> Check Python version during setup

- brkt_cli/aws_service.py
- brkt_cli/encrypt_ami.py
- test.py
1. Metavisor does not support sriov. So, if guest instance has sriov support, then use legacy mode to create the encrypted ami.
2. Fix the HVM legacy path by removing the unencrypted and encrypted guests disks from the encryptor instance.
> Disable sriov support.

- brkt_cli/__init__.py
- test.py
When starting brkt-cli, check the code version against the list of
available versions on PyPI.  Exit if the code version is earlier than
the earliest available version.  If a newer version is available, log a
message that reminds the user to upgrade.  Add a --no-check-version
option to skip the version check.
> Check version on startup

- brkt_cli/encrypt_ami.py
Remove the warning and move the additon of sriovNetSupport attribute
to valid values at the initialization of the encrypt_ami module.
> Handle lack of sriovNetSupport attribute query in boto2.

- brkt
- brkt_cli/__init__.py
- brkt_cli/aws_service.py
- brkt_cli/encrypt_ami.py
- brkt_cli/encryptor_service.py
- brkt_cli/update_ami.py
- brkt_cli/validation.py
- setup.py
- test.py
Update all of the license blocks to reference the LICENSE file in brkt-
cli.  They incorrectly referenced the LICENSE file in the Bracket Java
SDK.
> Fix links to license file

- brkt_cli/__init__.py
- brkt_cli/encrypt_ami.py
- brkt_cli/encrypt_ami_args.py
- brkt_cli/encryptor_service.py
- brkt_cli/update_ami.py
- brkt_cli/update_encrypted_ami_args.py
- test.py
Adding ntp-server, a brkt-cli option to allow customers to override
the default NTP server in ntp configuration of metavisor.
This option is supported for both encryption and update process.
ntp-server is provided as user-data to the encryptor/updater instance.
Error out if ntp-server is not a valid host name or ipv4 address.
Finally, handle errors reported by the Bracket Updater instance.
> Allow customers to configure use of their own NTP servers in metavisor.

- brkt_cli/__init__.py
- test.py
When updating an encrypted AMI, check the value of its BrktEncryptorAMI
tag.  Don't proceed with the update if the tag value matches the
proposed metavisor AMI ID.  We skip this check if the user specifies
--no-validate.
> Don't allow updating an encrypted AMI with the same metavisor AMI

- brkt_cli/__init__.py
- brkt_cli/aws_service.py
- test.py
When checking for image name collisions, search only the images owned by
the current AWS account and not public images.
> Check the owner's images for name collisions

- brkt_cli/__init__.py
- brkt_cli/encrypt_ami.py
- brkt_cli/update_ami.py
- test.py
After attaching the encrypted root volume to the guest instance, wait
for the device mapping to become available before continuing.  Add a
unit test for this code path.  Print more details when a virtualization
type mismatch occurs.
> Wait for root disk to attach

- .travis.yml
- brkt_cli/__init__.py
- brkt_cli/encrypt_ami.py
- brkt_cli/encrypt_ami_args.py
- brkt_cli/proxy.py
- brkt_cli/user_data.py
- setup.py
- test.py
Add a new --proxy option for specifying one or more HTTPS proxies to use
during encryption.  Proxies are specified as host:port.  When proxies
are specified, we generate a proxy.yaml file and pass it to the
encryptor instance via user data.
To do:
* Specify HTTPS proxy when updating an AMI
* Read proxy.yaml from a file
> Pass HTTP proxy config during encryption

- brkt_cli/encrypt_ami.py
- brkt_cli/user_data.py
- test.py
[Squashed version of PR#167]
The encryptor AMI only looks for multi-part MIME userdata in the case that it finds the userdata to be compressed.  So we'll compress it, which is probably a good thing to do anyway.
Also, make the test_brkt_env_encrypt() test expect the userdata to be in compressed MIME format, rather than plain JSON.
> Compress userdata for encryptor instance

- brkt_cli/encrypt_ami.py
In some customer envrionments, customers use http_proxy
environment variables in the shell they are encrypting images
and it is needed for the cli when validating version. This
change will ensure we don't try to communicate to encryptor
instances with private ips through the proxy by appending the
encryptor private ip to the NO_PROXY environment variable.
> Use NO_PROXY talking to private encryptor ip

- brkt_cli/encrypt_ami_args.py
- brkt_cli/update_encrypted_ami_args.py
--ntp-servers allow customers to configure locally hosted ntp-servers
for time synchronization. This commit makes this option visible.
> Add --ntp-servers to brkt-cli.

- setup.py
Oauth2client requires 0.1.7 and something
else requires 0.1.8. If pip resolves Oauth2client
first the brkt cli installs incorrectly. This
ensures we have a sufficiently up to date version
of pyasn1
> Adds pyasn1 0.1.9 to setup.py

- brkt_cli/__init__.py
- brkt_cli/encrypt_ami_args.py
- brkt_cli/proxy.py
- test.py
Add a --proxy-config-file option to the encrypt-ami subcommand.  This
allows the user to pass in the entire proxy.yaml file, when specifying
proxies as host:port is not enough.
> Load proxy.yaml from a file

- brkt_cli/encrypt_gce_image.py
- brkt_cli/update_gce_image.py
GCE commands now give more meaningful errors
and clean up encryptor instances if necessary
Testing: Encrypted and updated an image
> Make GCE commands more error tolerant

- brkt_cli/__init__.py
- brkt_cli/encrypt_gce_image.py
- brkt_cli/launch_gce_image.py
- brkt_cli/launch_gce_image_args.py
Guest root disk now matches encrypted guest
snapshot size instead of defaulting to 25GB
Also adds option for specifying instance type
in the launch-gce-image command
Testing: launched a range of instance types
from 21GB snapshot.
> Launch-gce-image resizes guest to snapshot size

- brkt_cli/__init__.py
- brkt_cli/encrypt_ami.py
- brkt_cli/encrypt_gce_image.py
- brkt_cli/update_ami.py
- brkt_cli/update_encrypted_ami_args.py
- test.py
Add --proxy and --proxy-config-file options to the update-encrypted-ami
subcommand.
Add a _get_proxy_config() utility function for loading proxy.yaml
content.  This function is called during encryption and update.
Add a combine_user_data() function, which generates the gzipped MIME
blob that is passed to the metavisor.  This allows us to write dedicated
unit tests for this logic.
Minor terminology changes:
* user data: the actual user data bytes that are sent to the instance
* brkt env: host/port of the api service and HSM proxy
* brkt config: the dictionary that stores brkt env, ntp servers, etc.
> Add proxy support to update-encrypted-ami

- brkt_cli/update_ami.py
This is similar to what we do when encrypting an AMI. If the
updater has a private IP we don't talk to it using any configured
http proxy.
> Add NO_PROXY when we are updating an AMI

- brkt_cli/__init__.py
- brkt_cli/encrypt_ami.py
- brkt_cli/encrypt_gce_image.py
- brkt_cli/update_ami.py
- brkt_cli/update_encrypted_ami_args.py
- test.py
This reverts commit 606df19b8c2941b8405cc68f44053b47296a426a.
(we must first have Metavisor support MIME userdata when in 'updater' mode -- sorry I neglected to consider this during the original PR)
> Revert "Add proxy support to update-encrypted-ami"

- brkt_cli/__init__.py
- test.py
The AWS API can return an empty response when the account doesn't have
access to the image.  Handle this case when validating the an AMI.
Consolidate the image validation logic, so that we validate all images
in a consistent manner.
Update _validate_encryptor_ami(), so that it raises ValidationError,
like the other validation functions.
> Handle empty response when validating the encryptor image

- brkt_cli/__init__.py
- brkt_cli/gce_service.py
Now the cli ensures the encryptor image
exists and no image exists with the same
name as the output image for gce.
> Adds checks to gce commands

- brkt_cli/__init__.py
- brkt_cli/encrypt_ami.py
- brkt_cli/gce_service.py
- brkt_cli/util.py
- test.py
When updating an encrypted AMI, handle the possibility that the new name
may exceed 128 characters.  Refactor the image name generation logic
into a separate function, to make it more testable.  Move
append_suffix() into the util module, since it's now called from
multiple places.
> Handle long image name when updating

- brkt_cli/__init__.py
- brkt_cli/encrypt_ami.py
- brkt_cli/encrypt_gce_image.py
- brkt_cli/encryptor_service.py
- brkt_cli/gce_service.py
- brkt_cli/update_ami.py
- brkt_cli/update_gce_image.py
- brkt_cli/util.py
- test.py
Some code shared by gce and aws (and likely other csps)
was in encrypt_ami.py. It makes more sense for this code
to be in the generic encryption service file.
Testing: encrypted and updated gce images
> Move generic encryption methods to encryptor_service.py

- brkt_cli/__init__.py
- brkt_cli/aws_service.py
- brkt_cli/encrypt_ami.py
- brkt_cli/encrypt_ami_args.py
- brkt_cli/update_ami.py
- brkt_cli/update_encrypted_ami_args.py
- test.py
Add a --guest-instance-type option to the encrypt-ami and update-
encrypted-ami subcommands.  This allows the user to specify the guest
instance type when the default of m3.medium is incompatible with the
guest AMI.
Clean up the original test_instance_type() test, so that it switches on
the AMI ID instead of making assumptions about the order in which
instances are launched.
> Support specifying the guest instance type

- brkt_cli/__init__.py
If no brkt_env option is provided to encrypt
or update gce image commands it defaults to
the prod endpoints.
Testing: ran encrypt_gce_image and update_gce_image
without --brkt-env and verified the prod endpoints
were passed through userdata.
> Brkt_env defaults to prod for gce commands

- brkt_cli/__init__.py
- brkt_cli/launch_gce_image_args.py
Added a startup-script option to the launch-gce-image command
to provide an ability to specify a startup script during instance
launch. This can be used for testing cloud-init and similar
testing (see YETI-822).
Jira: YETI-822
> Provide a means to add a startup-script for GCE instances

- brkt_cli/encrypt_gce_image.py
- brkt_cli/gce_service.py
- brkt_cli/util.py
Adds a retry method to utils. Also adds
execute_gce_api_call which wraps a googleapiclient
request object to make it retry-able.
API are wrapped with a retry where appropriate.
Example of an appropriate place: wait_instance
where we are waiting for a resource we created
Example of a bad place to put it: create_disk
if that fails it almost definitely is a real
problem
It's also worth noting that if for some reason
someone wanted to retry create_disk they could
I only added retries to methods in the gce_service
that clearly need it.
Testing: encrypted and updated a gce image
> Adds retry to gce api calls that need it

- README.md
Remove the --updater-ami option from the sample output of update-
encrypted-ami.  It's now a hidden option that's meant to be used in
development.
> Remove --updater-ami from the update-encrypted-ami example

- brkt_cli/launch_gce_image.py
Configure the instance disk to be always deleted upon instance termination. If there is a better way to do this, then let me know.
> Delete guest disk upon instance termination

- brkt_cli/__init__.py
- brkt_cli/aws/__init__.py
- brkt_cli/aws/encrypt_ami_args.py
- brkt_cli/aws/update_encrypted_ami_args.py
- brkt_cli/module.py
Move AWS argument parsing into a new brkt_cli.aws module.  Load the
module by name and call its interface to initialize command line
arguments.  The next step will be to move all of the AWS-specific code
into brkt_cli.aws so that it isn't intermingled with other CLI and GCE
logic.
> Add support for subcommand modules

- brkt_cli/__init__.py
- brkt_cli/aws/__init__.py
- brkt_cli/module.py
Update AWSModuleInterface.run_subcommand() and the callsite to return
the exit status.  Failing to do this caused the function to return None,
which resulted in an exit status of 1.
> Return exit status from run_subcommand()

- brkt_cli/__init__.py
- brkt_cli/aws/__init__.py
- brkt_cli/aws/aws_service.py
- brkt_cli/module.py
Add an init_logging() method to ModuleInterface, which allows submodules
to configure logging.  Move boto logging setup into the aws submodule.
Set the default log level on the root logger, per the usual convention,
and suppress boto logging explicitly.
Import boto.vpc in aws_service.  Somehow an unrelated code change caused
boto.vpc.regions() to start failing.
> Initialize logging in submodules

- brkt_cli/__init__.py
- brkt_cli/aws/__init__.py
- brkt_cli/aws/encrypt_ami_args.py
- brkt_cli/aws/update_encrypted_ami_args.py
- brkt_cli/module.py
Add -v and --verbose to the encrypt-ami and update-encrypted-ami
subcommands.  Several users have gotten confused because -v was
specified as an option to the top-level brkt command.
> Add -v option to subcommands

- brkt_cli/encrypt_gce_image.py
- brkt_cli/gce_service.py
- test_gce.py
This will prevent us from creating an undesirable authorized_keys
file on the guest root disk.
> Block project wide ssh keys when we launch guest for encryption

- brkt_cli/__init__.py
- brkt_cli/encrypt_gce_image.py
- brkt_cli/encrypt_gce_image_args.py
- brkt_cli/gce_service.py
- brkt_cli/update_encrypted_gce_image_args.py
- brkt_cli/update_gce_image.py
- test_gce.py
1. Added a keep-encryptor flag to keep the encryptor image, even
if encryption/update fails due to any reason. Default action would
be to delete the encryptor image upon completion or failure.
2. Increased the retries waiting for disk and attached a catch exception statement (this fixes YETI-824) 
3. Updated unit tests
4. Ran unit tests locally and verified that it passed
> Cleanup GCE image

- README.md
The list of dependencies has become stale.  Removing it, so that we
don't have to keep it current.  It's no longer necessary, now that we're
using pip/setuptools to automatically install dependencies.
> Remove dependencies from README

- .travis.yml
- brkt_cli/__init__.py
- brkt_cli/jwt/__init__.py
- brkt_cli/jwt/test_jwt.py
- setup.py
Add a generate-jwt command for generating a JWT that is used to launch
an encrypted instance.
$ ./brkt generate-jwt -h
usage: brkt generate-jwt [-h] [--cnc N] [--exp TIMESTAMP] [--nbf
TIMESTAMP]
--signing-key PATH [-v]
Generate a JSON Web Token for launching an encrypted instance.
Timestamps can
be either a Unix timestamp in seconds or ISO 8601
(2016-05-10T19:15:36Z).
-h, --help          show this help message and exit
--cnc N             Maximum number of concurrent instances
--exp TIMESTAMP     Token expiration time
--nbf TIMESTAMP     Token is not valid before this time
--signing-key PATH  The private key that is used to sign the JWT. The
key
must be in PEM format.
-v, --verbose       Print status information to the console
$ ./brkt generate-jwt --cnc 12 --exp …
> Add generate-jwt command

- brkt_cli/update_gce_image.py
Pass the keep_encryptor flag so that the encryptor image does not get cleaned up when specified via command line args.
> Pass the keep_encryptor flag for image updates

- brkt_cli/__init__.py
Make sure that the run() method of the subcommand returns the result
status as an integer.  This should help us find problems with status
codes without having to run the integration tests.
> Check subcommand result

- brkt_cli/aws/update_ami.py
When updating an image, we ignore any attached volumes except for
the "known" one's (sda1, sda2, sda3, sda5 for PV and sda and sdf
for PV). For any attached volume, we should simply preserve the
original volume type configured with the AMI.
This was tested by:
1. Launching an encrypted AMI
2. Attaching a couple of EBS volumes at sdc and sdd
3. Creating a new image snapshot of the running Solo instance
4. Updating the AMI created in step 3 above
5. Verifying that the volume type in the updated AMI matched with the original AMI
Jira: YETI-942 #resolve
> Preserve volume type for any attached volumes

- brkt_cli/jwt/__init__.py
- brkt_cli/jwt/jwk.py
- brkt_cli/jwt/test_jwt.py
Add a key id field ("kid") to the generated JWT.  To calculate the key
id, we:
1) Load the public key that's associated with the signing key.
2) Convert the public key to a JWK.
3) Calculate the thumbprint of the JWK, as specified in RFC 7638.
> Add "kid" field to the generated JWT

- brkt_cli/__init__.py
Require that subcommand lookup succeeds.  We now use the new subcommand
infrastructure for all subcommands.
Move the version check into a separate function, and call it before
running the subcommand.  A previous commit inadvertently switched the
order of these operations.
Testing:
* python -m unittest discover
* hack the hardcoded version and manually test the version check
* manually run encrypt-ami, update-encrypted-ami, and generate-jwt
> Clean up subcommand handling

- brkt_cli/__init__.py
- brkt_cli/jwt/__init__.py
- brkt_cli/jwt/test_jwt.py
- brkt_cli/test_util.py
- brkt_cli/util.py
Add a --claim option, which allows the user to add JWT claims as
name/value pairs.  Refactor the name/value parsing code, so that the
same code is used for claims and tags.
> Add --claim option to generate-jwt

- brkt_cli/gce/__init__.py
Raise exception if both args are pass to
encrypt or update gce-image
Testing: checked that providing both options
causes exception and passing one does not
> Check encryptor_image and image_bucket args

- brkt_cli/aws/encrypt_ami_args.py
- brkt_cli/aws/update_encrypted_ami_args.py
- brkt_cli/jwt/__init__.py
- brkt_cli/jwt/test_jwt.py
Change the name of the generate-jwt subcommand to make-jwt, per Adam's
suggestion.  "Make" is shorter and consistent with the existing
make_user_data command in cephalopod.
> Rename generate-jwt to make-jwt

- brkt_cli/__init__.py
- brkt_cli/make_user_data/__init__.py
```
$ ./brkt make-user-data -h
usage: brkt make-user-data [-h] [--jwt JWT] [-v]
Generate MIME multipart user-data that is passed to Metavisor and cloud-
init when running an instance.
-h, --help     show this help message and exit
--jwt JWT      JSON Web Token that the encrypted instance will use to
authenticate with the Bracket service. Use the make-jwt
subcommand to generate a JWT.
-v, --verbose  Print status information to the console
```
> Add make-user-data command for generating cloud-init user-data

- .travis.yml
Retain the pip cache, to speed up Travis builds.  More info at
https://docs.travis-ci.com/user/caching/
> Retain the pip cache between builds

- brkt_cli/aws/__init__.py
Commit f63b1e1eaaf0afcc6590d0635adaf3a8313a6105 changed the signature of
_validation_region() and broke update-encrypted-ami.  Fix
command_update_encrypted_ami() so that it passes the entire values
object instead of the region name.
> Pass the entire values object into _validation_region()

- brkt_cli/jwt/__init__.py
- brkt_cli/jwt/test_jwt.py
* Handle invalid timestamp and PEM file path.
* Move all CLI parsing code into setup_make_jwt_args() so that the
Subcommand implementation is leaner.
* Use a global SigningKey for all JWT unit tests instead of generating
multiple times.  Unit test run time is back under 1 second!
> make-jwt validation and test cleanup

- brkt_cli/aws/aws_service.py
- brkt_cli/gce/gce_service.py
- brkt_cli/test_util.py
- brkt_cli/util.py
- test.py
Update aws_service so that it uses the retry() function in the util
module.  Add the ability to use a RetryExceptionChecker to determine
whether we should retry.  We need this in order to check
EC2ResponseError.error_code.  Change the retry interval to a time period
instead of counting the number of attempts, so that the caller doesn't
have to do math to determine the timeout.
Remove the retry_boto decorator and replace it with a retry_boto()
function.  This gives us the flexibility of retrying either in
AWSService or in the higher-level application code.  Add unit tests for
util.retry().
> Consolidate the retry logic

- brkt_cli/jwt/__init__.py
When the signing key can't be parsed, give more specifics about the type
of key that we support.
> Improve error message when signing key can't be parsed

- brkt_cli/jwt/__init__.py
- brkt_cli/jwt/test_jwt.py
Fix the JWT logic so that it generates a valid token.
* Pass separators when encoding JSON, to avoid whitespace.
* Encode JSON as UTF-8.
* Use SHA-384 when signing.
* Move the kid field from the payload to the header.
Testing: successfully ran verify-jwt in Yeti
> Fix JWT generation

- brkt_cli/aws/encrypt_ami.py
This allows us to easily identify/find/archive console logs
from failed runs.
> Have named suffix for instance console log

- brkt_cli/__init__.py
A version check error shouldn't brkt-cli from working.  If there's an
eror when downloading the list of supported versions, print the error
message and continue.  Also, add a timeout in case the request to
pypi.python.org hangs.
> Don't abort when version check fails

- brkt_cli/gce/__init__.py
- brkt_cli/gce/encrypt_gce_image.py
- brkt_cli/gce/encrypt_gce_image_args.py
- brkt_cli/gce/gce_service.py
- brkt_cli/gce/update_encrypted_gce_image_args.py
- brkt_cli/gce/update_gce_image.py
- test_gce.py
Allows user to specify a non-default network
to launch encryptor instances in
Testing: encrypted and updated gce images
> Add --network option to update and encrypt gce

- brkt_cli/aws/encrypt_ami.py
- brkt_cli/aws/update_ami.py
- brkt_cli/gce/encrypt_gce_image.py
Replace "raise e" with "raise", so that the original traceback is
preserved.  Remove a gratuitous try/except in the GCE codebase.
> Preserve traceback when re-raising exceptions

- brkt_cli/aws/aws_service.py
- brkt_cli/aws/test_aws_service.py
- brkt_cli/util.py
Handle two obscure errors that occasionally pop up in the field.  I
believe that the AWS service returns 503 when the request rate limit has
been exceeded for a given account.  I'm not sure what causes
ssl.SSLError, but it has been reported a couple of times.
To handle these errors, we:
* Check for these cases in BotoRetryExceptionChecker.
* Wrap every AWS call with retry_boto()
Also, make BotoRetryExceptionChecker.error_code_regexp an optional
argument.  If the regexp isn't specified, we check for the two cases
above.
Change "raise e" to "raise" in util.retry(), so that the original
traceback is preserved.
> Handle edge case errors when calling the AWS API

- brkt_cli/aws/encrypt_ami.py
http is liable to be cached by an internet proxy without the
right headers.
https is also the right thing to do from a security perspective.
Note that now, this verifies the s3 server certificate so your
python version should support this.
Testing done:
- ran locally on my Mac and virtualenv
> Use https for getting amis from s3

- brkt_cli/__init__.py
- test.py
* Per Grant, the 'kid' field should be in the header and not in the payload.  The JWTs created by 'brkt make-jwt' already put the 'kid' in the header.
Testing:
* Ran unit tests.
* Ran "make-user-data --jwt <data output by 'brkt make-jwt'>"
> Moved 'kid' field from payload to header of JWT

- brkt_cli/__init__.py
- brkt_cli/aws/__init__.py
Check for debug logging on the Logger object instead of using
values.verbose.  values.verbose only works when -v is specified at the
top level, not at the subcommand level.
Clean up duplicate logging initialization code.
> Fix verbose logging check when printing exceptions

- brkt_cli/aws/__init__.py
- brkt_cli/aws/aws_service.py
- brkt_cli/aws/encrypt_ami_args.py
- brkt_cli/aws/update_encrypted_ami_args.py
Add two new options to the encrypt-ami and update-encrypted-ami
subcommands that allow the caller to change the default timeout and
initial sleep time when retrying AWS operations:
--retry-timeout
--retry-initial-sleep-seconds
We use these options internally, to avoid intermittent AWS service
failures when running concurrent encryption processes in integration
tests.
> Add internal options for retry behavior

- brkt_cli/aws/encrypt_ami.py
- brkt_cli/aws/update_ami.py
- brkt_cli/gce/encrypt_gce_image.py
- brkt_cli/gce/update_gce_image.py
- brkt_cli/make_user_data/__init__.py
- brkt_cli/test_user_data.py
- brkt_cli/user_data.py
- brkt_cli/util.py
* Instead of putting the JWT in a brkt-file with dest path /var/brkt/ami_config/token.jwt, put the JWT in the brkt_config dictionary with key 'identity_token'.
Testing:
* Ran unit tests
* Ran 'brkt make-user-data -jwt <file_with_jwt>'
> Put JWT in brkt_config, not as file

- brkt_cli/aws/__init__.py
- brkt_cli/aws/aws_service.py
This code is no longer used since validation is done with
argparse.
> Remove unused status port validation cruft

- brkt_cli/aws/__init__.py
- brkt_cli/aws/encrypt_ami.py
- brkt_cli/aws/encrypt_ami_args.py
- brkt_cli/user_data.py
- brkt_cli/util.py
* Adds --ca-cert arg to 'encrypt-ami' command
(TODO: add it to update-ami, encrypt-gce-image and update-gce-image)
[rebased and fixed version of #322, which superseded #308]
> Add --ca-cert arg to encrypt-ami

- Dockerfile
- README.md
Update ca-certificates when building a Docker container.  This avoids
cert verification issues when getting the AMI list from S3 via https.
Add --rm docker run samples, so that people who copy/paste don't end up
with container cruft from every run.
Update the sample AMI ID to be an HVM AMI, since that's now the default.
> Update ca-certificates when building the Docker container

- brkt_cli/make_user_data/__init__.py
[squashed version of #329]
* In #321, I switched the '--jwt' input to make-user-data be  a filename instead of a string.  But other commands use JWTs as strings, so make-user-data should follow that convention.
> Made JWT input be string for make-user-data

- brkt_cli/__init__.py
- brkt_cli/aws/__init__.py
- brkt_cli/aws/encrypt_ami.py
- brkt_cli/aws/encrypt_ami_args.py
- brkt_cli/aws/test_aws_service.py
- brkt_cli/aws/test_encrypt_ami.py
- brkt_cli/aws/test_update_ami.py
- brkt_cli/aws/update_ami.py
- brkt_cli/aws/update_encrypted_ami_args.py
- brkt_cli/gce/__init__.py
- brkt_cli/gce/encrypt_gce_image.py
- brkt_cli/gce/encrypt_gce_image_args.py
- brkt_cli/gce/gce_service.py
- brkt_cli/gce/launch_gce_image_args.py
- brkt_cli/gce/update_encrypted_gce_image_args.py
- brkt_cli/gce/update_gce_image.py
- brkt_cli/instance_config.py
- brkt_cli/instance_config_args.py
- brkt_cli/make_user_data/__init__.py
- brkt_cli/oauth_requests.py
- brkt_cli/test_instance_config.py
- brkt_cli/test_user_data.py
- brkt_cli/test_util.py
- brkt_cli/user_data.py
- brkt_cli/util.py
- test_gce.py
* Created InstanceConfig class with methods to generate userdata and gce_userdata.  Its ctor takes a 'values' list, as returnd by argparse.parse_args().
* Reduced the input args to the 'encrypt' and 'update' functions for aws and gce (substituting an InstanceConfig arg).
* Added helper functions in instance_config_args to be used by commands that launch Metavisor instances.
* This has the effect of making all instance-launching commands (encrypt-ami, update-encrypted-ami, encrypt-gce-image, update-encrypted-gce-image, launch-gce-image) now consistently support these args:
--brkt-env, --proxy, --proxy-config-file, --ntp-server, --jwt.
Also, all the 'creator' mode commands (all the above except launch-gce-image) now support the --ca-cert arg as well.
* Added unit tests for the new …
> Consolidate instance config arg handling

- brkt_cli/aws/__init__.py
- brkt_cli/aws/diag.py
- brkt_cli/aws/diag_args.py
- brkt_cli/aws/share_logs.py
- brkt_cli/aws/share_logs_args.py
brkt share-logs subcommand allows users to share a snapshot of the Bracket
system log volume from an instance in the customer AWS account
with the Bracket AWS account. This is intended to be used by customers to
aid Bracket debugging in cases where logs are not reaching the Bracket
servers (e.g. cases with network connecitivity issues from an instance).
brkt diag subcommand will launch an instance with the log volume attached
and readable. It can grab the logs from an instance given instance
id or from a snapshot id. The diag instance is launched with
a specified ssh key with a security group that has port 22 open.
Sample developer use case: 
* Run `brkt diag --instance-id`
* SSH to debug instance and view logs
Sample customer user case: 
* Customer runs `brkt share-logs`
* Bracket …
> Adds `brkt share-logs`, `brkt diag` 

- brkt_cli/aws/encrypt_ami.py
- brkt_cli/aws/test_update_ami.py
We moved the SLEEP_ENABLED global from encrypt_ami to util a while back.
This commit removes the original variable and cleans up the remaining
callsite.
> Clean up old SLEEP_ENABLED code

- brkt_cli/__init__.py
- brkt_cli/aws/__init__.py
- brkt_cli/aws/share_logs_args.py
- brkt_cli/brkt_jwt/__init__.py
- brkt_cli/gce/__init__.py
- brkt_cli/get_public_key/__init__.py
- brkt_cli/make_key_pair/__init__.py
- brkt_cli/make_user_data/__init__.py
Use a custom HelpFormatter to sort options for all commands in
alphabetical order.  Rename share-logs' positional argument to be in all
caps, to follow convention.
> Sort command line options

- brkt_cli/aws/diag_args.py
- brkt_cli/aws/encrypt_ami_args.py
- brkt_cli/aws/share_logs_args.py
Turns --no-save-encryptor-logs to --save-encryptor-logs which is
False by default and hidden.
Cleanup snapshot and instance id flags for the share-logs and
diag commands.
> Default don't snapshot failed encryptor log volume

- brkt_cli/aws/__init__.py
When updating an encrypted AMI, make sure that the AMI exists before
proceeding.
> Validate the encrypted AMI id when updating

- brkt_cli/aws/diag_args.py
- brkt_cli/aws/share_logs_args.py
Change the metavar name from SNAPSHOT-ID and INSTANCE-ID to ID, to
follow convention and make the usage output a little more concise.
-------------
```
$ ./brkt share-logs -h
usage: brkt share-logs [-h] [--snapshot ID] [--instance ID] [--no-
validate]
--region NAME [-v]
Share logs from an existing encrypted instance.
--instance ID  The instance with Bracket system logs to be shared
--no-validate  Don't validate instance has AMI with Bracket tags
--region NAME  AWS region (e.g. us-west-2)
--snapshot ID  The snapshot with Bracket system logs to be shared
-h, --help     show this help message and exit
-v, --verbose  Print status information to the console
```
> Shorten metavar for diag and share-logs

- brkt_cli/aws/diag.py
FreeBSD didn't like our NetBSD disk label so the log partition
for HVM could not be read.
Use NetBSD official images and change the mountpoint and output
to user correspondingly.
Testing done:
- tested diag for a PV and metavisor instance and verified
mounts.
> Use NetBSD instead of FreeBSD for diag instances

- README.md
Move the latest version number to the top of the document.  Add a link
to the tag, so users can read the release notes.
> Update README for 1.0.2

- brkt_cli/aws/__init__.py
- brkt_cli/aws/test_update_ami.py
- brkt_cli/aws/update_ami.py
- brkt_cli/aws/update_encrypted_ami_args.py
I ran into an issue when updating an AMI on behalf of a customer
where AWS did not have the the capacity to launch c3.large
instances for more than an hour. As a workaround I had to hack
the brkt cli to use an m3.medium instead. We should add an
instance type arg for anywhere we launch an instance so we
aren't beholden to AWS capacity issues.
Makes the default updater type to m3.medium. The previous was
c3.large to match the encryptor instance type. However, we
don't need a beefy instance type for updating since we don't
do any resource intensive operations during updating.
> Adds arg for updater instance type

- brkt_cli/__init__.py
- brkt_cli/aws/test_aws.py
- brkt_cli/encryptor_service.py
- brkt_cli/gce/update_gce_image.py
- brkt_cli/instance_config_args.py
- brkt_cli/test_instance_config.py
- brkt_cli/test_util.py
- brkt_cli/util.py
- test.py
Address some refactoring issues that came up as a result of work on
BracketEnvironment.  Commit these changes separately, so that they don't
muddy up the followup commmit.
Move the BracketEnvironment from the encryptor_service package into the
brkt_cli package.  It's a higher-level system configuration construct
and doesn't apply to the encryptor instance.
Move add_brkt_env_to_brkt_config() from util to brkt_cli, also because
it's a higher-level concept.  util should be for lower-level code.
Move TestEncryptAMIBackwardsCompatibility into the AWS codebase, since
it is AWS-specific.
> Move BracketEnvironment and TestEncryptAMIBackwardsCompatibility

- brkt_cli/__init__.py
- brkt_cli/gce/__init__.py
- brkt_cli/instance_config_args.py
- brkt_cli/test_instance_config.py
- test.py
Support specifying the Yeti environment by its domain
Add a new hidden --service-domain option that specifies the Yeti
environment that the metavisor (and soon, the CLI) will talk to.
When a domain is specified (e.g. stage.mgmt.brkt.com), we infer the
following hosts and ports:
* internal API (RPC): yetiapi.<domain>:443
* HSM proxy: hsmproxy.<domain>:443
* external API: api.<domain>:80
Always send the Yeti environment to metavisor, so that behavior is
clearly defined and does not differ between CSPs.
> Support specifying a domain for --brkt-env

- brkt_cli/aws/__init__.py
It's a package-level variable.  No need to pass it around.
> Don't pass around the log object

- brkt_cli/gce/__init__.py
- brkt_cli/gce/encrypt_gce_image.py
- brkt_cli/gce/gce_service.py
Waits longer for the encryptor image to show
up. fails more gracefully
if the image isn't created for some reason
> Handle encryptor retrieval failure better

- brkt_cli/__init__.py
- brkt_cli/aws/__init__.py
- brkt_cli/aws/test_encrypt_ami.py
- brkt_cli/gce/__init__.py
- brkt_cli/instance_config_args.py
- brkt_cli/make_user_data/__init__.py
- brkt_cli/test_instance_config.py
- test.py
Split BracketEnvironment parsing out from the rest of the values passed
when constructing InstanceConfig.  This allows callsites to determine
whether to specify BracketEnvironment or not.
Background: in commit bfe70c372f95730964a0f9c3366aa94a8806cf64 we
started always sending the Yeti environment to Metavisor.  This created
problems when launching a GCE image.  If the user didn't specify the
environment on the command line, we'd send the prod endpoints, which
would inadvertently override the Metavisor defaults.
> Don't require brkt-env when launching a GCE instance

- brkt_cli/__init__.py
HTTPError.code is an integer, not a string.
> Fix server response error log message when validating JWT

- brkt_cli/brkt_jwt/__init__.py
- brkt_cli/make_key/__init__.py
- brkt_cli/make_user_data/__init__.py
Expose these commands, now that we have back-end support for JWT auth.
> Expose the make-key, make-token, and make-user-data commands

- brkt_cli/gce/launch_gce_image.py
Displays the GCE instance name and public IP which avoids the user from having to lookup the GCE UI (or use other means) to obtain the IP of the launched instance.
> Display GCE instance name and IP upon successful launch

- brkt_cli/__init__.py
- brkt_cli/aws/__init__.py
- brkt_cli/brkt_jwt/__init__.py
- brkt_cli/config/__init__.py
- brkt_cli/config/test_config.py
- brkt_cli/gce/__init__.py
- brkt_cli/gce/encrypt_gce_image_args.py
- brkt_cli/get_public_key/__init__.py
- brkt_cli/make_key/__init__.py
- brkt_cli/make_user_data/__init__.py
- brkt_cli/subcommand.py
- brkt_cli/util.py
- setup.py
This commit adds infrastructure to allow subcommands to read default
values from a config file stored in ~/.brkt/config. In order to use
the new infrastructure, subcommands must implement the setup_config()
method. In it, they should register any options they want to pull
from the config.
A new sub-command, "config", has been added to the cli. This lets
users list, set, get, and unset options in the config. It is
modeled after "kubectl config".
Finally, the first consumer of the config infrastructure is the
"encrypt-gce-image" sub-command. The "project", "network", and
"zone" options may be specified via the config.
> Add support for specifying options in a config file

- brkt_cli/encryptor_service.py
We're improving error handling in the Metavisor.  It's possible that
Metavisor will send an error code that the CLI isn't expecting.  If this
happens, print the failure code, so that the user has an idea of what
went wrong.  Also, print the entire status structure when running in
verbose mode.
> Print unexpected failure code

- brkt_cli/brkt_jwt/__init__.py
- brkt_cli/brkt_jwt/test_jwt.py
Remove the cnc option from the make-token command.  We are no longer
using this claim to limit the number of instances.
> Remove support for the cnc claim

- brkt_cli/aws/encrypt_ami.py
- brkt_cli/aws/test_aws_service.py
- brkt_cli/aws/test_encrypt_ami.py
- brkt_cli/aws/test_update_ami.py
- brkt_cli/aws/update_ami.py
When encryption or update fails, stop the metavisor instance before
attempting to collect the console log.  The current behavior in AWS is
that the console log isn't immediately available unless the instance
state changes.
> Stop encryptor before getting console log

- brkt_cli/aws/__init__.py
Remove support for the BRACKET_ENVIRONMENT environment variable.  This
variable was a switch that would tell brkt-cli whether to use the
staging or production build of Metavisor.  This is no longer being used.
Developers who want to use a specific Metavisor AMI can use the hidden
--encryptor-ami option.
> Remove support for BRACKET_ENVIRONMENT

- brkt_cli/encryptor_service.py
We can download encrypted guest images from either AWS S3 or Google Cloud Storage (GCS).  So make the status message generic.
> Change "S3" to "Cloud Storage" in status message

- brkt_cli/aws/__init__.py
- brkt_cli/aws/test_encrypt_ami.py
- brkt_cli/gce/__init__.py
- brkt_cli/instance_config_args.py
- brkt_cli/make_user_data/__init__.py
- brkt_cli/test_instance_config.py
Move BracketEnvironment handling back into make_instance_config() and
rename it to instance_config_from_values().  The behavior was becoming
confusing because BracketEnvironment was handled at the callsite, but
other config stuff was parsed from values.
The current behavior is a bit funky because the logic switches on the
metavisor mode.  I think it's better than the alternative, since
callsites don't have to worry about explicitly handling every option
that goes into InstanceConfig.
Move the add_argument() calls for --brkt-env and --service-domain inside
the mode check.  We don't want to allow these options when launching a
GCE image.  When launching, Metavisor should talk to the Yeti
environment that was specified at encryption time.
> Clean up InstanceConfig parsing and arguments

- brkt_cli/encryptor_service.py
- brkt_cli/test_encryptor_service.py
Handle new new failure codes returned during encryption or update.
Print a user-friendly message when they occur.  Move failure code
handling into a separate function, to keep wait_for_encryption()
concise.
> Handle new encryption/update failure codes

- brkt_cli/encryptor_service.py
When encryption or update fails, log the entire data structure returned
by Metavisor at error level.  This gives us more context about the
failure, even if the user isn't running with -v.
> Log status when encryption fails

- brkt_cli/__init__.py
If the token auth check returns 400, log the message returned by the
server.  This can happen when Yeti uses a 3rd party JWK server and the
token does not have a customer claim.
> Abort if the token is invalid

- brkt_cli/gce/__init__.py
- brkt_cli/gce/launch_gce_image.py
- brkt_cli/gce/launch_gce_image_args.py
Provide an option to specify a network when launching GCE images via the CLI tool. Defaults to the 'default' network.
> Add network flag to GCE launch image

- brkt_cli/gce/encrypt_gce_image.py
- brkt_cli/gce/update_gce_image.py
Log the host and port that we use to monitor encryption/update progress,
to help the user diagnose networking issues.
> GCE: log the host and port of the encryptor/updater service

- brkt_cli/aws/encrypt_ami.py
Set the default timeout in wait_for_instance() to 10 minutes, to avoid
intermittent failures when running integration tests.  Clean up
docstring.
> Set default instance state timeout to 10 minutes

- brkt_cli/__init__.py
- brkt_cli/aws/__init__.py
- brkt_cli/config/__init__.py
- brkt_cli/gce/__init__.py
- brkt_cli/get_public_key/__init__.py
- brkt_cli/make_key/__init__.py
- brkt_cli/make_user_data/__init__.py
Add help to all subcommands.  This causes argparse to print a brief
description next to each subcommand in the top-level usage output.  Add
descriptions to GCE commands.  Capitalize config command descriptions,
so that they are consistent with the convention that we've been
following to date.
I couldn't figure out a way to sort the list of subcommands with
descriptions.
$ ./brkt -h
usage: brkt [-h] [-v] [--version] [--no-check-version]
{config,diag,encrypt-ami,encrypt-gce-image,launch-gce-image
,make-key,make-token,make-user-data,share-logs,update-encrypted-ami
,update-gce-image}
...
Command-line interface to the Bracket Computing service.
positional arguments:
{config,diag,encrypt-ami,encrypt-gce-image,launch-gce-image,make-key
,make-token,make-user-data,share-logs,update-encrypted-ami,up …
> Add help to subcommands, usage cleanup

- README.md
- aws.md
- gce.md
Add docs for the make-key and make-token commands.  Move docs for AWS
and GCE commands into separate pages, to keep the main page shorter.
> Documentation update

- brkt_cli/instance_config.py
When adding files with brkt-files parts in userdata, we must use Unix-style path separators for the destination file names, even when the brkt-cli command is being run on Windows.
Testing:
* Ran unit tests on Linux (no failures)
* Ran unit tests on Windows; this fix resolves 3 failures in existing
tests (still need to fix temp file issue with
test_util.TestReadPrivateKey.test_read_private_key()
> Use posixpath for dest files in userdata

- brkt_cli/__init__.py
- brkt_cli/aws/__init__.py
- brkt_cli/gce/__init__.py
- brkt_cli/subcommand.py
Write debug log output to a temporary file unless the user specified -v.
If the command succeeds, we delete the file.  If the command fails, we
print the location of the debug log.
> Write debug log to a temp file

- brkt_cli/gce/__init__.py
- brkt_cli/gce/gce_service.py
- brkt_cli/gce/launch_gce_image.py
- test_gce.py
launch-gce-image no longer append 'guest'
to the instance name. However because the
root disk and guest disk cant have the same
name '-s' is appended to instance_name and
used as the name for the disk created from
the encrypted guest root snapshot
the launch command now validates the instance
name before trying to launch the instance
> Don't append guest to instance name

- brkt_cli/gce/__init__.py
- brkt_cli/gce/gce_service.py
- test_gce.py
Provide a more meaningful error if the GCE project entered is invalid. This was tested locally.
> Add method to validate if GCE project exists

- requirements.txt
- setup.py
google-api-python-client doesn't support oauth2client version 3 or
later.  Update the requirements list so that we use the latest 2.x
version.
> Don't allow oauth2client 3.x or later

- brkt_cli/aws/encrypt_ami.py
- brkt_cli/aws/test_aws_service.py
- brkt_cli/aws/test_encrypt_ami.py
Do a better job of cleaning up the guest and encryptor instances.  We
didn't handle the case where an exception was thrown inside
run_guest_instance() or _run_encryptor_instance().  Add exception
handling and cleanup inside both of those functions.
> Clean up guest and encryptor instances

- brkt_cli/aws/update_encrypted_ami_args.py
We shouldn't assume that the user wants to run in a given region.
> Remove default value for update-encrypted-ami --region

- brkt_cli/aws/encrypt_ami.py
If the guest root volume is PIOPS, then the IOPS parameter needs to be copied over to the encrypted AMI
> Copy the IOPS parameter from the right place

- brkt_cli/__init__.py
- brkt_cli/aws/__init__.py
- brkt_cli/config/__init__.py
- brkt_cli/config/test_config.py
- brkt_cli/gce/__init__.py
- brkt_cli/instance_config_args.py
- brkt_cli/test_instance_config.py
- brkt_cli/util.py
This commit makes environment a first class concept in the CLI. Environments are
defined as the set of Yeti backends that the CLI/MV talk to. Users declare new
environments via the `set-env` config subcommand. For example, to define the
`foo.com` environment, one does:
> brkt config set-env foo --service-domain foo.com
Use the `use-env` config subcommand to switch between environments:
> brkt config use-env stage
Use the `list-envs` config subcommand to list all the declared environments. A
leading `*` indicates the current environment.
> ./brkt config list-envs
brkt-hosted
* foo
>
The `brkt-hosted` environment corresponds to our hosted production environment.
It is the default environment and may not be changed by users.
Use the `get-env` config subcommand to get the details of an …
> Add support for user-specified environments stored in config

- brkt_cli/aws/encrypt_ami.py
Copy the IOPS properly for PIOPS volumes. For other volume types, ignore the IOPS settings.
Tested this locally with AMIs using standard, GP2 and PIOPS volumes.
> Copy IOPS properly for PIOPS volumes

- brkt_cli/gce/__init__.py
- brkt_cli/instance_config_args.py
* Delete BRKT_ENV_PROD as it is no longer used.
* Remove the default_brkt_env arg to setup_instance_config_args() as it is no longer used.
Testing:
* Ran unit tests
* Ran 'brkt encrypt-ami'
> Clean up brkt_env defaulting

- brkt_cli/gce/encrypt_gce_image.py
This variable was set outside the try/except block, so it ended up being
a no-op.  Also don't pass the Exception argument to raise, to preserve
the original traceback.
> Remove unused encryptor_launched variable

- brkt_cli/aws/__init__.py
- brkt_cli/aws/encrypt_ami.py
- brkt_cli/aws/encrypt_ami_args.py
- brkt_cli/aws/test_aws_service.py
- brkt_cli/aws/test_encrypt_ami.py
Add a hidden --no-terminate-encryptor-on-failure option.  When this
option is specified and encryption fails, we terminate the guest
instance but not the encryptor.  This allows a developer to connect to
the encryptor instance to diagnose the problem.
> Add a hidden option for keeping the encryptor running after failure

- brkt_cli/aws/update_ami.py
If the guest root volume type is PIOPS, copy over the IOPS settings during an image update.
This was verified locally by updating AMIs with and without PIOPS volumes.
> Copy over IOPS of guest root during image update

- brkt_cli/make_user_data/__init__.py
- brkt_cli/make_user_data/test_make_user_data.py
- brkt_cli/make_user_data/testdata/test_guest_fqdn.out
To allow customers to specify the instance's FQDN in the certs used for North-South (VPN) tunnels, add the "--guest-fqdn" option to make-user-data.
> Add --guest-fqdn option to make-user-data

- brkt_cli/make_user_data/__init__.py
- brkt_cli/make_user_data/testdata/test_guest_fqdn.out
To convey the FQDN to use for North-South cert requests, pass in a vpn.yaml file (to be stored in /var/brkt/instance_config/) rather than putting the field in the brkt-config part.
> Use vpn.yaml brkt-file instead of brkt-config

- brkt_cli/gce/__init__.py
- brkt_cli/gce/launch_gce_image.py
- brkt_cli/gce/launch_gce_image_args.py
Provide a subnetwork argument to launch a GCE image in a specific subnet. This was tested in my personal account.
> Add sub-network to GCE image launch command

- brkt_cli/gce/launch_gce_image_args.py
Re-adding the subnetwork argument to the launch-gce-image command.
This was accidentally removed in commit: a599ad9a6b4a4afdcdbcd67284efff9c2de34d16.
Tested this locally by launching a new GCE image.
> Re-add subnetwork argument to launch-gce-image

- brkt_cli/esx/__init__.py
- brkt_cli/esx/encrypt_vmdk_args.py
- brkt_cli/esx/esx_service.py
- brkt_cli/esx/update_encrypted_vmdk_args.py
1. Raise exception if environment variables for vcenter username and password are not set.
2. Gracefully exit if SCSI controller is not found in the Encryptor VM.
3. Fix the destination of memory variable.
> Raise exceptions for missing environment variables.

- brkt_cli/gce/launch_gce_image_args.py
- brkt_cli/instance_config_args.py
The guest FQDN is required for north-south configuration to get enabled on the instance. This option allows setting this user-data value when launching GCE instances. This is very useful in testing and potentially automation of north-south.
Was tested locally in my account.
> Allow passing guest FQDN when launching GCE instances

- brkt_cli/esx/encrypt_vmdk_args.py
- brkt_cli/esx/esx_service.py
- brkt_cli/esx/update_encrypted_vmdk_args.py
1. Default ovf-image should be prod.
2. Only retain release directories in the bucket.
> Switch default bucket to prod bucket

- brkt_cli/esx/__init__.py
- brkt_cli/esx/esx_service.py
- brkt_cli/instance_config.py
- test_esx.py
Passing userdata in MIME - as AWS & GCE do - allows ESX to use all shared
command line options (e.g. proxy settings). This change also removes
redundant logic in the ESX creation of userdata.
> Add all common command line options to ESX

- setup.py
This avoids using the latest version which is broken on MAC.
> Fix pyvmomi version to be between 5.5.0 and 6.0.0

- brkt_cli/esx/__init__.py
- brkt_cli/esx/encrypt_vmdk.py
- brkt_cli/esx/update_vmdk.py
1. Pass no-teardown value from user argument to esx-service.
Without this change, configuration of no-teardown has no impact.
2. Print final output (template/ovf/ova name) to stdout.
This makes ESX output the same as AWS where the output of the operation
is written to stdout and not stderr.
> Fix teardown implementation

- brkt_cli/esx/rescue_metavisor_args.py
The intention of this operation is to change the core upload
location of the MV VM being identified by its name.
Hence, moving the vm-name to a positional argument.
> Make the VM name a positional argument

- brkt_cli/gce/launch_gce_image.py
We did not do this before, and it results in us printing "None" to
stdout when someone issues the "brkt --version" command.
> Return instance-name on gce-launch-image

- setup.py
Missing a comma after a package named in the 'install_requires' list.
> Fix typo in install_requires in setup.py

- brkt_cli/__init__.py
- brkt_cli/aws/__init__.py
- brkt_cli/esx/__init__.py
- brkt_cli/gce/__init__.py
- brkt_cli/instance_config_args.py
- brkt_cli/make_user_data/__init__.py
Users may now specify a token in their config file that will be
used as by default when encrypting, updating, or launching images.
> Add token to config

- brkt_cli/esx/esx_service.py
Forcing anonymous s3 access to the bucket locked us out from
using non-public buckets. This change addresses that by allowing
the use aws credentials (if they exist).
If no credentials are found in the environment, we will fall back
to an anonymous connection.
> Make esx encryption use aws credentials to get image from s3

- brkt_cli/gce/__init__.py
- brkt_cli/gce/encrypt_gce_image.py
- brkt_cli/gce/encrypt_gce_image_args.py
- brkt_cli/gce/update_encrypted_gce_image_args.py
- brkt_cli/gce/update_gce_image.py
the no cleanup option prevents the encryptor
from being deleted. In case more debugging
is required than just looking at the logs
Testing: ran encrypt-gce-image with the no-cleanup
option and interrupted it
> Add no-cleanup option to gce encrypt and update

- brkt_cli/esx/__init__.py
- brkt_cli/esx/encrypt_vmdk.py
- brkt_cli/esx/encrypt_vmdk_args.py
- brkt_cli/esx/esx_service.py
- brkt_cli/esx/update_encrypted_vmdk_args.py
- brkt_cli/esx/update_vmdk.py
- test_esx.py
1. Make update-vmdk and encrypt-vmdk input options consistent.
2. Unhide the OVF/OVA options.
3. Fix clone disk for use with esx host only.
4. Remove manifest validation with update-vmdk.
5. Remove use SIGALRM if not present.
6. Remove use of rm with os.remove.
7. Set template name to be the VM name when used with esx-host.
> Fix update-vmdk and use-esx-host functionality and usage.

- brkt_cli/brkt_jwt/__init__.py
The name and value pairs for a key tag must only contain alpha-numeric and hyphen characters.
> Add validation for NAME=VALUE tags

- brkt_cli/esx/encrypt_vmdk.py
- brkt_cli/esx/esx_service.py
- brkt_cli/esx/update_vmdk.py
Not having .ovf extenstion in the MV image name makes
the user interface consistent between getting MV image
from S3 or locally.
> MV encrypted image name should not include .ovf.

- brkt_cli/esx/esx_service.py
Boto tries to fetch the AWS credentials from metadata service before
doing a S3 download. If it does not get those credentials (which are
not present in ESX), it prints a confusing info message which looks
like an error. Hence, making the change to print only fatal messages
from boto.
> Print only fatal messages from boto

- brkt_cli/aws/encrypt_ami.py
FeeBSD metavisors have support for sriov drivers so we
don't have to play games with guest AMI's that require
sriov.
This preserves any 'pay as you go' licensing for such
guests.
> No need to slip into 'legacy' mode for FreeBSD metavisors

- brkt_cli/gce/gce_service.py
Since the same method is used to validate both an image and instance name, making the error message(s) more generic.
> Better error message for instance name validation

- brkt_cli/aws/__init__.py
Remove _validate_log_instance() and _validate_log_snapshot() functions,
which don't do anything.
> Removed unused validation functions in the AWS code

- brkt_cli/gce/__init__.py
- brkt_cli/gce/gce_service.py
If project_exists receives a 400 http error return
false (indicating the project doesn't exists).
For any other exception raise
> Handle gce api failure better for project_exists

- requirements.txt
- setup.py
1.5.x doesnt work on linux. This ensures
a compatible version of the python cryptography
library is installed
> Ensure cryptography version is compatible

- brkt_cli/__init__.py
- brkt_cli/aws/__init__.py
- brkt_cli/aws/diag_args.py
- brkt_cli/aws/encrypt_ami_args.py
- brkt_cli/aws/share_logs_args.py
- brkt_cli/aws/update_encrypted_ami_args.py
- brkt_cli/gce/__init__.py
- brkt_cli/subcommand.py
Update the AWS command line spec to follow our new convention.  Move the
following commands:
* encrypt-ami -> aws encrypt
* update-encrypted-ami -> aws update
* diag -> aws diag
* share-logs -> aws share-logs
Hide the old commands and log a deprecation warning when they are used.
Refactor the AWS module, so that the run() functions in both the old
and new commands call the same code.
The GCE and VMware commands will be updated in separate commits.
> Update the AWS command line spec

- brkt_cli/config/__init__.py
- brkt_cli/gce/__init__.py
Update the GCE command line spec to follow our new convention. Move the following commands:
- encrypt-gce-image -> gce encrypt-image
- update-gce-image -> gce update-image
- launch-gce-image -> gce launch-image
Hide the old commands and log a deprecation warning when they are used.
Refactor the GCE module so that the run() functions in both the old
and new commands call the same code.
Migrate the GCE config options based on the new command convention.
The AWS and ESX commands will be udpated in separate commits.
> Update GCE command line spec

- brkt_cli/gce/__init__.py
Fix missing change in https://github.com/brkt/brkt-cli/pull/486 causing
errors when running GCE commands.
> Fix GCE refactor after merge

- brkt_cli/config/__init__.py
- brkt_cli/gce/__init__.py
An attribute error was being reported when trying to save the
CLI Config. This happens in environments where the CLI Config
has never been initialized. This change ensures that the CLI
Config is attempted to be saved only if needed.
Also moved the _unlink_noraise method so that it can be called as a
common method instead of being restricted to the ConfigSubcommand class.
> Attribute error when running brkt-cli

- brkt_cli/esx/update_encrypted_vmdk_args.py
Hide the use-esx option as it is provided only for backward compatibility.
WIth the new command convention, the use-esx flag settings will get
implied automatically.
> Hide use-esx option

- brkt_cli/esx/__init__.py
Traceback error reported when running rescue-metavisor. The _get_vcenter_password
method had been updated to accept one argument, but the invocation from the
rescue-metavisor method was not updated to reflect this change.
> Traceback error when running rescue-metavisor

- brkt_cli/esx/__init__.py
- brkt_cli/esx/encrypt_vmdk_args.py
- brkt_cli/esx/encrypt_with_esx_host_args.py
- brkt_cli/esx/esx_service.py
- brkt_cli/esx/rescue_metavisor_args.py
- brkt_cli/esx/update_encrypted_vmdk_args.py
- brkt_cli/esx/update_with_esx_host_args.py
Enable SSL cert validation for vCenter
- Changed the no-validate argument to no-verify-cert to reflect the correct usage
- Use the no-verify-cert flag to control SSL cert validation with vCenter
- Remove unused no-validate flag for encrypt/update with-esx-host subcommand
> Enable SSL cert validation for vCenter

- brkt_cli/esx/esx_service.py
Retaining the OVF file after encryption will cause update of the same ova to fail later as untarring it to create ovf will fail.
> Remove the OVF file after converting it to OVA.

- brkt_cli/gce/encrypt_gce_image_args.py
- brkt_cli/gce/update_encrypted_gce_image_args.py
The GCE config options were being references using the old names
because of which they were not being parsed (and utilized) correctly
with the GCE specific brkt-cli commands. With this change, even after
the config options are migrated to the new format, the config
options would be utilized both with the new command syntax (for
e.g. *brkt gce encrypt*) as well as the old command syntax (for
e.g. *brkt encrypt-gce-image*)
> Parse GCE config options correctly

- brkt_cli/__init__.py
When the token fails authorization, log the name of the host.  This
makes the error a bit more intuitive for users who access multiple
environments.
> Log the hostname when auth fails

- brkt_cli/__init__.py
Don't write the debug log to a temp file when a validation error or
keyboard interrupt.  The temp debug log is only useful when diagnosing
unexpected errors during long-running operations.
> Don't write debug log unless the command starts running

- brkt_cli/brkt_jwt/__init__.py
- brkt_cli/brkt_jwt/test_jwt.py
We treat "any" as a reserved word.  Don't allow it for the claim name or
value.  Stop returning True from validate_name_value(), since we throw
ValidationError when validation fails.
> Don't allow "any" for claim name or value

- brkt_cli/esx/esx_service.py
CLI reports an error when connecting to vCenter. This happened since the verify flag was initialized in the parent class only. Verified locally and waiting on the automation tests to pass.
> Error when connecting to vCenter

- brkt_cli/esx/esx_service.py
1. Pass the flag down to vcenter service initialization.
2. Set context to None in case --no-verify-cert is used.
> Fix disabling of verify certification

- brkt_cli/instance_config_args.py
- brkt_cli/make_user_data/__init__.py
Remove the following options from the make-user-data command:
--status-port
--brkt-env
--service-domain
The status port is only used during encryption.  brkt-env and service-
domain shouldn't be used when launching an instance, since we don't want
the same Metavisor talking to two different services.
Clean up the wording for several command line options, to make the
description clearer.
--------------
~~~~
$ ./brkt make-user-data -h
usage: brkt make-user-data [-h] [--ntp-server DNS_NAME]
[--proxy HOST:PORT | --proxy-config-file PATH]
[--token TOKEN] [-v]
[--guest-user-data-file PATH:TYPE]
Generate MIME multipart user-data that is passed to Metavisor and cloud-init
when running an instance.
--guest-user-data-file PATH:TYPE
User-data file and MIME content type to be …
> Clean up make-user-data arguments and usage

- brkt_cli/__init__.py
Don't print the default value when it is None or a boolean.  These cases
are already clear in the usage output.  The default value ends up being
either gratuitous, or confusing for options with negative names, like
--no-validate.
To do this, we copy the code from argparse.ArgumentDefaultsHelpFormatter
and do nothing if we detect either case.
```text
$ ./brkt aws encrypt -h
usage: brkt aws encrypt [-h] [--encrypted-ami-name NAME]
[--guest-instance-type TYPE] [--pv] [--no-validate]
--region NAME [--security-group ID] [--subnet ID]
[--tag KEY=VALUE] [-v] [--ntp-server DNS_NAME]
[--proxy HOST:PORT | --proxy-config-file PATH]
[--status-port PORT] [--token TOKEN]
ID
Create an encrypted AMI from an existing AMI.
positional arguments:
ID                    The guest AMI that will be encrypted …
```
> Be more selective when printing default values in usage

- brkt_cli/__init__.py
- brkt_cli/aws/__init__.py
- brkt_cli/brkt_jwt/__init__.py
- brkt_cli/make_key/__init__.py
- brkt_cli/util.py
In some cases, we log tracebacks only when verbose logging is enabled.
We used to log the exception if log.isEnabledFor(logging.DEBUG) returned
True.
This code broke when we started writing debug log output to a temp file
(commit 9b4a6538d256602d8d5b885441858e6e8f6bc4d6).  After the logging
change, the call to log.isEnabledFor(logging.DEBUG) always returned
True.
With this commit, we fix all of the callsites, so that they log the
traceback with log.debug(..., exc_info=1).  This has the desired effect
of always writing tracebacks to the temp file, while only writing it to
stderr when the verbose logging flag is set.
> Log tracebacks at debug level

- brkt_cli/esx/esx_service.py
If you supplied an encryptor ovf image without the .ovf file ending it
chopped off the last characters and you ended up with an invalid file
name. We now handle both cases.
> Handle omitted file ending

- brkt_cli/aws/__init__.py
- brkt_cli/aws/diag.py
- brkt_cli/aws/encrypt_ami_args.py
- brkt_cli/aws/test_aws.py
- brkt_cli/aws/update_encrypted_ami_args.py
We no longer support the paravirtual version of Metavisor.  Remove the
--pv option and related code.
> Remove support for PV Metavisor

- brkt_cli/__init__.py
If an exception is raised during the version check and the exception
doesn't have a message, use the class name as the message.
> Clean up the version check error

- brkt_cli/aws/aws_service.py
- brkt_cli/aws/test_aws.py
- brkt_cli/aws/test_aws_service.py
We are now calling create_image() instead of register_image().  Remove
the unused application code.  We still use this function for registering
dummy images in the unit test code.
> Remove unused register_image code

- brkt_cli/esx/__init__.py
- brkt_cli/esx/encrypt_vmdk_args.py
- brkt_cli/esx/esx_service.py
- brkt_cli/esx/update_encrypted_vmdk_args.py
A user may want to use a proxy to connect to the internet
from the host which is running the brkt-cli, while all other
(internal) connections do not require the proxy. The outside
(internet) connection is to S3 while the internal connections
goes to the local vCenter (which at most times has a well known
host name), to an ESX host on which the encryptor/updater VM
is deployed (whose IP most times is not known, but the list
of ESX hosts may available)  and to the encryptor VM itself
(whose IP comes from DHCP, hence is definitely not known
beforehand). This change allows the user to specify a HTTP(s)
proxy and port to allow the brkt-cli to use it for the
outbound connection to S3.
> Add HTTP(s) proxy for S3 connections

- brkt_cli/gce/__init__.py
- brkt_cli/gce/gce_service.py
- brkt_cli/gce/launch_gce_image.py
- brkt_cli/gce/launch_gce_image_args.py
GCE instances support local SSD scratch disks that are physically
attached to the server which hosts the virtual machine (similar to
instance store volumes on AWS). However unlike the persistent disks,
the SSD scratch disks can only be attached at instance launch time.
This change allows the user to specify the number of SSD scratch
disks to attach to the instance at launch time (Default: 0, Max: 8)
using the --ssd-scratch-disks option with the "gce launch" sub-command.
> Provide ability to add SSD scratch disks with instance launch

- brkt_cli/esx/__init__.py
If the http-s3-proxy argument is not defined when encrypting or
updating a vmware image, then the command was failing with an
object attribute error. The change ensures that the proxy
elements are passed only if they are specified, else it is
skipped.
> Fix error when no S3 Proxy is specified

- brkt_cli/esx/__init__.py
Following up from the previous commit, adding the changes to
ignore the proxy for VMWare updates if it is not specified.
> Fix error when no S3 Proxy is specified for VMWare updates

- brkt_cli/__init__.py
Close the debug log handler before attempting to remove the file.  This
avoids open file descriptor issues on Windows.
> Close debug log handler before deleting the file

- brkt_cli/esx/__init__.py
- brkt_cli/esx/encrypt_vmdk_args.py
- brkt_cli/esx/encrypt_with_esx_host_args.py
- brkt_cli/esx/esx_service.py
- brkt_cli/esx/update_encrypted_vmdk_args.py
- brkt_cli/esx/update_with_esx_host_args.py
- test_esx.py
1. Add support for changing the network name to which the
NIC in the Encryptor VM connects to.
2. Add support for allowing Encryptor VM NIC to be a
VirtualPort or a VirtualPortGroup in a VDS.
> Add support for setting the network-name for the Encryptor VM

- brkt_cli/gce/encrypt_gce_image_args.py
- brkt_cli/gce/update_encrypted_gce_image_args.py
The encryptor-image-bucket argument needs to be specified if you
are using a custom (or pre-production) image for encrypting or
updating an image. Since this is required only for internal
testing, this argument is being hidden.
> Hide the encryptor-image-bucket argument

- brkt_cli/__init__.py
- brkt_cli/aws/__init__.py
- brkt_cli/aws/aws_service.py
Check the state of the --verbose option instead of the log level before
writing user-data to a temp file.
With commit 9b4a6538d256602d8d5b885441858e6e8f6bc4d6, we started writing
the debug log to a temp file.  This caused
log.isEnabledFor(logging.DEBUG) to always return true.  The side effect
is that we started always writing user-data to a temp file.
> Don't log user-data unless --verbose was specified

- brkt_cli/brkt_jwt/__init__.py
Make the signing key path a positional argument, since it's required and
the token is derived from the key.  Hide the old --signing-key option
and log a deprecation warning when it's used.
```
$ ./brkt make-token -h
usage: brkt make-token [-h] [--claim NAME=VALUE] [--customer UUID]
[--exp TIMESTAMP] [--nbf TIMESTAMP] [-v]
[SIGNING-KEY-PATH]
Generate a JSON Web Token for encrypting an instance or launching an encrypted
instance. A timestamp can be either a Unix timestamp in seconds or ISO 8601
(2016-05-10T19:15:36Z). Timezone offset defaults to UTC if not specified.
positional arguments:
SIGNING-KEY-PATH    The private key that is used to sign the JWT. The key
must be a 384-bit ECDSA private key (NIST P-384) in PEM
format.
--claim NAME=VALUE  JWT claim specified by name …
```
> make-token: make the signing key a positional argument

- brkt_cli/gce/gce_service.py
- brkt_cli/gce/launch_gce_image_args.py
By default, we were not deleting the boot disk for a GCE instance
launched using the "brkt gce launch" command, when the instance was
terminated. This change makes the boot disk deletion the default
behaviour and toggles the purpose of the --delete-boot argument.
Now if this argument is specified, then we will retain the boot
disk on instance termination.
> Delete boot disk by default for GCE instances

- brkt_cli/gce/encrypt_gce_image.py
A malformed logging call was causing us to drop the original exception
on the floor.  Fix logging, so that we know the original cause of
failure.
> Fix exception handling in encrypt_gce_image.create_image()

- brkt_cli/gce/encrypt_gce_image.py
- brkt_cli/gce/update_gce_image.py
The orchestration relies on the boot disk being around after
the updater/encryptor has terminated.
Minor fix to avoid getting console output after updater
has terminated.
> Don't auto-delete boot disk for encryptor/updater

- brkt_cli/aws/__init__.py
- brkt_cli/aws/encrypt_ami.py
- brkt_cli/aws/encrypt_ami_args.py
- brkt_cli/aws/test_aws.py
- brkt_cli/aws/test_encrypt_ami.py
- brkt_cli/aws/test_update_ami.py
- brkt_cli/gce/__init__.py
- brkt_cli/gce/encrypt_gce_image.py
- brkt_cli/gce/encrypt_gce_image_args.py
- brkt_cli/util.py
- test_gce.py
Bracket supports GCM and XTS encryption mode for the disks. By default
the guest root volume always was encrypted using GCM. This change
adds a new (hidden) --boot-disk-crypto-policy argument which allows
the user to override the default encryption policy for the (guest)
root volume. If 'default' is specified, then the default encryption
policy is determined from the encryptor image type (NetBSD vs FreeBSD).
Note that XTS is not supported with the NetBSD encryptor.
> Provide ability to specify crypto mode

- brkt_cli/__init__.py
- brkt_cli/gce/launch_gce_image_args.py
- brkt_cli/gce/update_encrypted_gce_image_args.py
- gce.md
The update and launch operations for GCE was updated to reflect the
correct operation being performed.
Also, updated the public_api_port to use the correct port based on the
brkt_env settings instead of always defaulting to 443.
> Update help string and docs to reflect correct operation

- brkt_cli/gce/encrypt_gce_image.py
Default the guest root volume crypto mode for GCE to XTS. This keeps
it consistent with the AWS encryption process.
> Default guest root crypto mode to XTS for GCE

- brkt_cli/proxy.py
If the proxy config file is malformed (not YAML), make sure that the
ValidationError has the message from the exception that was thrown.
> Fix error handling when parsing proxy.yaml

- brkt_cli/esx/__init__.py
- brkt_cli/esx/encrypt_vmdk.py
- brkt_cli/esx/encrypt_with_esx_host_args.py
- test_esx.py
- Add a hidden {--crypto-policy} optional argument to specify the
crypto policy for the guest root volume
- Default the crypto policy for the guest root volume to XTS to
bring it on par with AWS and GCE
- Updated tests
> Add XTS support for ESX encryption

- brkt_cli/esx/__init__.py
Assign the crypto policy value to the correct instance_config attribute
> Fix VMDK encryption failure

- brkt_cli/config/__init__.py
Use shutil.move() instead of os.rename() to move the config file.  This
handles the case where the user's temp directory and home directory are
on different volumes.
> Use shutil.move() to move config file

- brkt_cli/aws/aws_service.py
- brkt_cli/aws/encrypt_ami.py
- brkt_cli/aws/test_aws_service.py
Enable SRIOV support by default
- Irrespective of whether the guest image supports SRIOV or not
Bracket supports it and hence should be enabled on all images
encrypted using the new NetBSD Bracket encryptor
> Enable SRIOV supprot by default

- brkt_cli/esx/encrypt_vmdk_args.py
The crypto_policy argument needs to be supported for vCenter encryption
as well. It was previously added only for encryption directly on an
ESX host
> Add crypto_policy for vCenter encryption

- brkt_cli/make_user_data/__init__.py
- brkt_cli/make_user_data/test_make_user_data.py
Update the make-user-data command, so that it's a bit easier to test.
The work is now done by make_user_data.make() instead of the run()
method of the subcommand.
This change will be needed by upcoming change to all commands that print
formatted output to stdout.  make-user-data, make-key, make-token, and
get-public-key will all need a new option to print content to a file, so
that it doesn't get mangled by file redirection on Windows.
> Refactor make-user-data

- brkt_cli/argutil.py
- brkt_cli/brkt_jwt/__init__.py
- brkt_cli/get_public_key/__init__.py
- brkt_cli/make_key/__init__.py
- brkt_cli/make_user_data/__init__.py
- brkt_cli/util.py
Add an --out option to the make-key, get-public-key, make-token, and
make-user-data commands, which causes output to be written to a file
instead of stdout.
This option is necessary on Windows, because PowerShell writes
redirected output as UTF-16.  Python is unable to make sense of UTF-16.
For example, if you redirect the output of make-key to a file,
make-token will not recognize the file format.
Add a new argutil module, which will contain common command line
options.  Add a new function to util for writing output to either a file
or stdout.
> Add option to write to file instead of stdout

- brkt_cli/aws/__init__.py
Make the AWS commands on par with the other commands to ensure that
the brkt-cli picks up the environment configured in the brkt-cli
(defaults to Prod) if none is specified by the user via the
{{--service-domain}} or {{--brkt-env}} argument.
> Use the brkt config specified environment

- brkt_cli/aws/test_encrypt_ami.py
- brkt_cli/aws/update_ami.py
- brkt_cli/esx/esx_service.py
- brkt_cli/gce/update_gce_image.py
- brkt_cli/instance_config.py
- brkt_cli/instance_config_args.py
- brkt_cli/make_user_data/__init__.py
- brkt_cli/make_user_data/test_make_user_data.py
- brkt_cli/make_user_data/testdata/test_add_one_binary_brkt_file.out
- brkt_cli/make_user_data/testdata/test_add_one_brkt_file.out
- brkt_cli/make_user_data/testdata/test_add_two_brkt_files.out
- brkt_cli/make_user_data/testdata/test_brkt_files_with_guest_userdata.out
- brkt_cli/make_user_data/testdata/test_guest_userdata.out
- brkt_cli/make_user_data/testdata/test_proxy_and_one_brkt_file.out
- brkt_cli/make_user_data/testdata/test_token_and_one_brkt_file.out
- brkt_cli/make_user_data/testdata/test_unencrypted_guest.out
- brkt_cli/test_instance_config.py
- test_esx.py
* These changes enable running MV instances (launched from the usual 'creator' images/AMIs with unencrypted guest roots attached. Such instances must have 'solo_mode: metavisor' in the userdata; they may also need Yeti endpoints and Yeti CA certs included as well.
* Adds (hidden) --unencrypted-guest arg to make-user-data to allow MV instances to be launched with unencrypted guest root disks.
* Allow brkt env and CA certs to be included in userdata for instances in 'metavisor' mode.
* Ensure the solo_mode is always included in userdata (only new for 'metavisor' mode.
* Adapted unit tests to these new behaviors.
Testing:
* Ran updated unit tests.
* Encrypted instance in GCE.
* Generated userdata manually for various CLI inputs.
> Userdata changes for unencrypted guests

- README.md
- aws.md
Update the description to include VMware, keys, and tokens.
Update links, so that they point to our provider-specific docs.  Chances
are that the reader already knows what AWS, GCE, and VMware are.
Move networking requirements to the AWS page, since they differ by CSP.
We will add networking requirements for GCE and VMware in a subsequent
commit.
Rearrange the AWS page so that the usage sections are at the bottom.
They're just a reference.  The shorter, descriptive sections should be
higher up.
> Update front page and AWS docs

- brkt_cli/make_user_data/__init__.py
- brkt_cli/make_user_data/testdata/test_unencrypted_guest.out
* Instead of "true", use a boolean (true) for the flag to convey that it's OK to boot from an unencrypted guest.
> Use boolean for allow_unencrypted_guest

- esx.md
Added a networking requirement section in the ESX docs, since they
differ from other CSPs. Also added more descriptions about the
steps followed for encryption when using `encrypt-with-vcenter`
versus the `encrypt-with-esx-host` operands.
> Update ESX docs

- README.md
Add the --upgrade option to the command line example that shows how to
install the code at the tip of master.  When this option is not
specified, a subsequent of the same version becomes a no-op, even if new
code is merged into the GitHub repo.
> Add --upgrade to pip install example

- brkt_cli/__init__.py
Turned out that closing the log handler was not enough.  We also have to
manually close the temporary log file that we created.  Once we do this,
Windows is able to delete the file.
> Close the debug log file before deleting it

- README.md
- aws.md
- brkt_cli/esx/__init__.py
- brkt_cli/gce/__init__.py
- esx.md
- gce.md
Change "VMWare" to "VMware."  Only capitalize the first word in docs and
usage sections, per current convention.
> Fix typos in docs and command line usage

- brkt_cli/esx/esx_service.py
The Metavisor images are stored in S3 buckets in the format
{{<image_name>/<image_name>.ovf}}. The {{--metavisor-ovf-image-name}}
argument expects the bucket key, instead of the OVF file name. This
change allows the user to specify either the bucket key or the full
OVF image name and normalizes them accordingly to ensure ease of use.
> Normalize image name for S3 downloads

- aws.md
- brkt_cli/gce/__init__.py
- brkt_cli/gce/encrypt_gce_image.py
- brkt_cli/gce/encrypt_gce_image_args.py
- brkt_cli/gce/gce_service.py
- brkt_cli/gce/launch_gce_image.py
- brkt_cli/gce/launch_gce_image_args.py
- brkt_cli/gce/update_encrypted_gce_image_args.py
- brkt_cli/gce/update_gce_image.py
- gce.md
- test_gce.py
GCE provides ability to tag instances and subsequently these tags
can be used in the network/firewall rules. Hence firewall rules
can be specified based on specific instance tags, which can be
assigned at launch time to control the network communication(s)
required by the specific GCE instance.
Online docs hace also been updated to reflect the new arguments/
usage.
> Provide ability to tag GCE instances

- aws.md
- brkt_cli/aws/__init__.py
- brkt_cli/aws/diag_args.py
- brkt_cli/aws/encrypt_ami_args.py
- brkt_cli/aws/update_encrypted_ami_args.py
- Renamed AWS tag argument to --aws-tag to eliminate any confusion
with "Bracket tags" (or claims)
- Added a deprecation warning message if the old --tag argument
is used (that is still supported, but now is hidden)
- Updated the docs to reflect the update argument usage information
> Rename AWS tag argument

- aws.md
- brkt_cli/__init__.py
- brkt_cli/aws/diag_args.py
- brkt_cli/aws/encrypt_ami_args.py
- brkt_cli/aws/share_logs_args.py
- brkt_cli/aws/update_encrypted_ami_args.py
- brkt_cli/brkt_jwt/__init__.py
- brkt_cli/get_public_key/__init__.py
- brkt_cli/make_key/__init__.py
- brkt_cli/make_user_data/__init__.py
Suppress the -v option from subcommand usage output and log a warning
when the option is used.  Also update sample usage in AWS docs.
Back story: some of our subcommands support the -v (--verbose) option
and others don't.  It's more consistent to just have it at the brkt
command level than to make sure that every subcommand implements it.
> Deprecate -v at the subcommand level

- brkt_cli/gce/__init__.py
- brkt_cli/gce/launch_gce_image_args.py
The `brkt gce launch` command was not reading the brkt config
settings for some of the attributes. This update ensures that
the launch command is on par with the encrypt and update GCE
commands for reading the config settings.
> Read config variables for GCE Launch command

- setup.py
Make setup.py on par with the requirements.txt file and fix the
pyvmomi version depending on the local python version.
Pyvmomi version 6.0 (and higher) are not compatible with python
version 2.7.8 and older which requires the appropriate package
version to be selected depending on the python version being used.
> Fix pyvmomi version depending on python version

- brkt_cli/gce/__init__.py
* For 'gce launch', don't try to get the brkt-env from the CLI config.
* If we factor in the CLI config when determining the brkt-env for 'gce launch' then we will always get a brkt-env from the CLI config (the endpoints may be for Prod); that makes it easy to accidentally use Prod endpoints when launching instances encrypted with other envs (when the image was encrypted using --service-domain or --brkt-env rather than using the endpoints in the current config).
> Ignore endpoints from config for 'gce launch'

- brkt_cli/argutil.py
Update the help wording, so that we don't assume that --out is only used
for private keys.
> Clean up --out option description

- brkt_cli/__init__.py
- brkt_cli/auth.py
- brkt_cli/yeti.py
Add a top-level auth command that authenticates with the Bracket service
and prints an API auth token.  This command can be used by developers
and scripts that need to make calls to the Bracket REST API.  Update the
existing token validation code to use the same yeti module.
The next step will be to add login/logout commands (probably under
config), which use the yeti module to authenticate and stores the API
token in the user's config file.
---------------
```
$ ./brkt auth -h
usage: brkt auth [-h] [--email ADDRESS] [--password PASSWORD] [--root-url URL]
[--out PATH]
Authenticate with the Bracket service. On success, print the JSON Web Token
that can be used to make calls to Bracket REST API endpoints.
--email ADDRESS      If not specified, show a prompt.
--out PATH …
```
> Add auth command

- brkt_cli/esx/encrypt_vmdk.py
When encrypting an image based off a local Metavisor/encryptor image,
the template-vm-name argument was being ignored and hence the VM
instance was always getting launched with the name as
'Encryptor-VM-<Date>'. This specifically causes problems when creating
encrypted ESX instances as it would be harder to identify the encrypted
instance when it does not use the user specified name.
> Use the template-vm-name argument when launch VM instance

- brkt_cli/__init__.py
- brkt_cli/config/__init__.py
- brkt_cli/test_util.py
- brkt_cli/util.py
Clean up and unit test the code that parses an endpoint string.  Update
the function to return a tuple of (host, port) instead of a dictionary.
This is more intuitive, since the function will always return exactly
two values.  Update the parsing logic to be more rigorous about catching
edge cases.  Raise ValidationError in all cases where the string is
invalid, so that behavior is consistent.  Add unit tests.
> Clean up endpoint parsing

- brkt_cli/esx/encrypt_vmdk.py
- brkt_cli/esx/encrypt_vmdk_args.py
- brkt_cli/esx/encrypt_with_esx_host_args.py
- test_esx.py
1. Teardown the instance (unless --no-teardown is used) on encryption failure.
2. Improve help messages.
> Fix error recovery during encryption on ESX.

- brkt_cli/esx/esx_service.py
Do not add the "/" suffix to the bucket/image name unnecessarily.
If a metavisor image name is specified, then it is OK to add a "/"
suffix to it to ensure that we are not overlapping with another
bucket with a similar prefix. However if the metavisor image name
is not specified and the CLI tries to sort thru' the buckets to
identify the latest one (used for Prod and Stage published images)
then the bucket/image name already has a "/" suffixed to it and that
causes the image download to fail as we are adding an additional "/"
to it.
> Fix the OVF image downloads

- brkt_cli/__init__.py
- brkt_cli/config/__init__.py
- brkt_cli/util.py
- brkt_cli/yeti.py
Add new commmands for logging in and out, and showing the current user.
The login command stores the user's API token in the config file and
logout unsets it.  logout is effectively an alias for "brkt config unset
api-token".
-------------
```
$ ./brkt config login --email me@example.com --password xxxxx
Logged into stage as me@example.com
$ ./brkt config list
api-token=eyJ0eXAi...
$ ./brkt config whoami
me@example.com
$ ./brkt config whoami --json
{
"email": "me@example.com",
"eula_accepted": true,
"eula_accepted_ts": 18446744011573954816,
"name": "Me Too",
"uuid": "ac5be98d-021a-4c31-8aee-0d90825102aa"
}
$ ./brkt config logout
$ ./brkt config whoami
Not logged in.  Please run brkt config login.
```
----------------
```
$ ./brkt config login -h
usage: brkt config login [-h] [--email …
```
> Add login, logout, whoami commands

- brkt_cli/auth.py
- brkt_cli/aws/__init__.py
- brkt_cli/config/__init__.py
- brkt_cli/esx/__init__.py
Hide the following subcommands from usage output:
auth
aws diag
aws share-logs
vmware rescue-metavisor
config login
config logout
config whoami
These commands are either internal or still in development.
> Hide internal subcommands

- brkt_cli/esx/esx_service.py
1. Report logging for sslerror so that the cli does not seem to be stuck.
2. Retry on ConnectionTimeouts in Windows.
> Fix connection issues in Windows.

- brkt_cli/esx/__init__.py
- brkt_cli/esx/encrypt_vmdk.py
- brkt_cli/esx/encrypt_vmdk_args.py
- brkt_cli/esx/encrypt_with_esx_host_args.py
- brkt_cli/esx/esx_service.py
- brkt_cli/esx/update_encrypted_vmdk_args.py
- brkt_cli/esx/update_vmdk.py
- brkt_cli/esx/update_with_esx_host_args.py
Previously the brkt-cli would always try to download the Metavisor
artifacts from S3 everytime an encrypt/update command is run, even
if the command fails subsequently do to issues with the vCenter/ESX
server and/or the specified parameters. With this change, we:
- Check if artifacts were already downloaded
- Check if the VMDK hash matches the manifest file
Only when one or more of the files are not found or the manifest hash
does not match the VMDK, do we try to download the artifacts from S3.
Additionally a hidden --no-cleanup option has been provided which can
be used in case the user does not want the downloaded artifacts to be
deleted after the encryption/update completes successfully. This is
especially useful in the case where the same artifact is required to
encrypt/update …
> Download artifacts from S3 only if required

- brkt_cli/esx/__init__.py
vCenter messes up the path of the vmdk during OVF
descriptor creation. Till the vCenter bug is fixed,
disable the OVF/OVA creation in Windows.
> Disable OVF/OVA creation in Windows.

- brkt_cli/esx/encrypt_vmdk.py
- brkt_cli/esx/esx_service.py
1. If there are no clusters in a datacenter, provide the ability to let
customers provide a host name to --vcenter-cluster.
2. Change the encryptor VM name to template name only if
the encryption is happening on esx host.
3. Fix error in detach disk.
> Add ability to provide host instead of cluster.

- brkt_cli/esx/update_vmdk.py
The launch_from_s3 method is now expecting a vm_name to be always
provided. For VMDK updates, this can be set to None.
> Pass an empty vm_name for VMDK update operation

- .travis.yml
- brkt_cli/esx/esx_service.py
- requirements.txt
- setup.py
There is inconsistent behavior with boto when downloading objects
from S3 where the bucket name contains dots:
https://github.com/boto/boto/issues/2836
To address this issue, VMware operations for fetching images from S3
are now using boto3. In addition to the new dependency on boto3, the
following issues have been addressed.
- The hidden --bucket-name argument now supports s3 buckets with dots
in the name
- The --metavisor-ovf-image argument can return the latest
metavisor image with exact or partial matches (e.g. 0-0-964 or
metavisor-0-0-964-g0cf0e0e62.ovf)
- If the --metavisor-ovf-image argument is _not_ provided, we
default to retrieving the latest modified image with a *latest* or
*release-* prefix
> Migrate to boto3 for retrieving S3 objects for esx_service

- brkt_cli/esx/esx_service.py
- test_esx.py
If a command takes a lot of time to execute, the vCenter connection
can go stale and expire. Handle this by checking the validity of
the connection before each function call.
> Handle vCenter connection expiry

- brkt_cli/__init__.py
- brkt_cli/brkt_jwt/__init__.py
- brkt_cli/config/__init__.py
- brkt_cli/config/test_config.py
- brkt_cli/test_version.py
- brkt_cli/version.py
- setup.py
- test.py
Check whether the version of brkt-cli is supported once a day, instead
of checking every time the command runs.  This avoids an unnecessary
network round trip.  It also makes it less likely that users will see
warnings in the command output when the PyPI REST API is not responding.
Add support for internal options to CLIConfig.  These options are used
by brkt-cli application code and not exposed to end users.  Store the
last version check timestamp as an internal option.
Move version-related code to a new module, to make the main brkt_cli
module more concise.
Add the ability to read CLIConfig from any file, instead of hardcoding
CONFIG_PATH.  This allows us to write unit tests that use StringIO.
> Check supported versions only once per day

- brkt_cli/make_user_data/__init__.py
- brkt_cli/make_user_data/test_make_user_data.py
- brkt_cli/make_user_data/testdata/test_unencrypted_guest.out
* The userdata produced by 'make-user-data --unencrypted-guest' should have the Yeti endpoints included; the endpoints are determined by the active config (defaulting to Prod endpoints for the default 'brkt-hosted' env).
Testing:
* Ran 'brkt make-user-data' with various options, including --unencrypted-guest
* Ran unit tests.
> Include endpoints in userdata for unencrypted-guest

- brkt_cli/aws/__init__.py
- brkt_cli/aws/encrypt_ami.py
- brkt_cli/aws/test_aws.py
The encryptor image name is used to determine valid images for AWS.
The image name is also used to determine the encryptor type (NetBSD
vs. FreeBSD) to make certain decisions (for cryptor policy and
sriovNetSupport). The image name format for FreeBSD encryptor
image was changed from brkt-avatar-freebsd-<date> to
metavisor-<branch>-<hash>. This change supports the new image name
format, but ignores the ealier image name format (brkt-avatar-freebsd).
> Support new encryptor image name format

- brkt_cli/aws/__init__.py
- brkt_cli/aws/aws_args.py
- brkt_cli/aws/diag_args.py
- brkt_cli/aws/encrypt_ami_args.py
- brkt_cli/aws/share_logs_args.py
- brkt_cli/aws/update_encrypted_ami_args.py
Add a new aws.region config key.  Update command line parsing to use
that value as the default.  Move the code that adds the --region option
into a new aws_args module, to avoid duplication.  Remove "(e.g.
us-west-2)" from the option description, to avoid "(e.g. us-west-2)
(default: us-east-1)".  Manually check that the region is set, now that
--region is no longer required.
> Add a config key for AWS region

- brkt_cli/brkt_jwt/__init__.py
- brkt_cli/brkt_jwt/test_jwt.py
- brkt_cli/config/__init__.py
- brkt_cli/yeti.py
When the user doesn't specify a signing key, get a launch token from the
Bracket service.  Add a new get_token() method to YetiService.
Add a new --brkt-tag option for specifying JWT claims.  This is
effectively the same thing as --claim, but with more validation of the
key and value.  We will deprecate --claim in a future commit.
> Update make-token to get token from the Bracket service

- brkt_cli/config/__init__.py
- brkt_cli/config/test_config.py
Update ConfigSubcommand and unit tests so that they don't overwrite
~/.brkt/config.  Move calls to CLIConfig.save_config() into the run()
method and don't call run() from unit tests, so that the config file
isn't modified by unit tests.  Move lower-level tests into
CLIConfigTestCase.  These tests call CLIConfig directly, without going
through the extra layer of ConfigSubcommand.
> Refactor config unit tests

- brkt_cli/auth.py
- brkt_cli/config/__init__.py
- brkt_cli/config/test_config.py
Update config.get_yeti_service() to get the API token from the
BRKT_API_TOKEN environment variable instead of the user's config.
Turned out that storing the API token in the config file isn't
convenient for scripting.  With an environment variable, the workflow is
the same for end users and scripts.
Update brkt auth to read the default API URL from config instead of
hardcoding to the production service.
> Get API token from an environment variable

- brkt_cli/esx/esx_service.py
If a VM takes too much time to clone, the find vm object
operation may fail. Handle the exceptions and retry.
> Handle long clone VM times

- brkt_cli/__init__.py
- brkt_cli/aws/__init__.py
- brkt_cli/gcp/__init__.py
Remove the code that validates a launch token by using it to
authenticate with the Bracket service.  This validation will break once
we decouple API tokens and launch tokens.
> Don't validate the launch token

- brkt_cli/auth.py
When --email is not specified, write the prompt to stderr instead of
stdout.  This allows the user to redirect auth output without getting
"Email: " in the output file.
> Write email prompt to stderr during auth

- brkt_cli/aws/__init__.py
- brkt_cli/brkt_jwt/__init__.py
- brkt_cli/esx/__init__.py
- brkt_cli/gcp/__init__.py
- brkt_cli/instance_config_args.py
- brkt_cli/yeti.py
Update the encrypt and update commands to get the Metavisor launch token
from the Bracket service if it's not specified on the command line.
With this change, the CLI will always send a launch token to Metavisor
when encrypting or updating.  If the launch token is not specified with
the --token option, we will now require that the $BRKT_API_TOKEN
environment variable be set.  This allows the CLI to authenticate and
get a launch token from the Bracket service.
> Get launch token from Bracket service during encryption

- brkt_cli/aws/aws_args.py
- brkt_cli/aws/diag_args.py
- brkt_cli/aws/encrypt_ami_args.py
- brkt_cli/aws/share_logs_args.py
- brkt_cli/aws/update_encrypted_ami_args.py
Consolidate the AWS command line options that appear in multiple
commands.  This ensures that naming and terminology is consistent across
commands.  Move the calls to add_argument() into functions in the
aws_args module and update callsites to call the new functions.
> Consolidate AWS args

- brkt_cli/esx/esx_service.py
OVF containing OVF properties cannot be launched on ESX hosts.
So remove the property section from the OVF descriptor when
launching on ESX hosts.
> Remove OVF property if using ESX host for encrytion

- brkt_cli/aws/__init__.py
- brkt_cli/aws/test_aws_service.py
- brkt_cli/aws/test_wrap_guest_image.py
- brkt_cli/aws/wrap_image.py
- brkt_cli/aws/wrap_image_args.py
- brkt_cli/esx/__init__.py
- brkt_cli/esx/esx_service.py
- brkt_cli/esx/wrap_image.py
- brkt_cli/esx/wrap_with_esx_host_args.py
- brkt_cli/esx/wrap_with_vcenter_args.py
- brkt_cli/gcp/__init__.py
- brkt_cli/gcp/wrap_gcp_image.py
- brkt_cli/gcp/wrap_gcp_image_args.py
- test_esx.py
- test_gce.py
A Bracket wrapped instance consists of a Metavisor which wraps the
guest root volume without encrypting it. This greatly speeds up the
process of deploying Bracket instances, providing all the benefits
of the Bracket Metavisor, without an encrypted guest root volume.
A new `wrap-guest-image` command has been added to all the three supported
CSPs which given a guest "image", would wrap the guest image with
the Bracket metavisor image and launch an instance using the same.
The launched instance should show up on your Bracket Management
Console (UI) within a few minutes. All Bracket supported features
including disk encryption (of attached disks), network policy and
network segmentation would be supported by such an instance.
The recommendation is once the instance is launched, the user …
> Provide ability to launch Bracket "wrapped" instance

- brkt_cli/argutil.py
- brkt_cli/brkt_jwt/__init__.py
- brkt_cli/brkt_jwt/test_jwt.py
- brkt_cli/gcp/__init__.py
- brkt_cli/instance_config_args.py
- brkt_cli/make_user_data/__init__.py
Add a --brkt-tags option to the following commands:
* aws encrypt
* aws update
* gcp encrypt
* gcp update
* gcp launch
* vmware encrypt-with-vcenter
* vmware encrypt-with-esx-host
* vmware update-with-vcenter
* vmware update-with-esx-host
When one or more tags is specified with the --brkt-tag option, we pass
the tags to the Bracket service at the time we generate the launch
token.  Yeti embeds the tags into the generated JWT as claims.
> Add --brkt-tags to encrypt and update commands

- brkt_cli/aws/__init__.py
- brkt_cli/aws/aws_service.py
- brkt_cli/aws/wrap_image.py
- brkt_cli/aws/wrap_image_args.py
- Added the missing verbose parameter, which was causing the
command to fail
- Print the `wrap-guest-image` in the top-level help of supported
commands
- Added a means to identify EBS optimized instances and pass the
flag accordingly
> Fixes to AWS `wrap-guest-image` command

- brkt_cli/gcp/encrypt_gcp_image_args.py
- brkt_cli/gcp/gcp_args.py
- brkt_cli/gcp/launch_gcp_image_args.py
- brkt_cli/gcp/update_encrypted_gcp_image_args.py
- brkt_cli/gcp/wrap_gcp_image_args.py
The encryptor_image is an optional argument for GCP commands which
is primarily used for internal testing or when a user has a local
encryptor image in their GCP account. As a result, it should be
hidden so as to not confuse users and also make it consistent
with similar commands for other CSPs.
Also consolidated the common GCP arguments into a single file.
> Hide the encryptor image option for GCP

- brkt_cli/aws/__init__.py
- brkt_cli/aws/wrap_image.py
- brkt_cli/esx/__init__.py
- brkt_cli/gcp/__init__.py
- brkt_cli/gcp/gcp_service.py
Added support for launch tokens to keep the wrap image command on
par with the encrypt/update commands. Also fixed an issue with
security group creation in AWS as no valid tags were being passed
with the request.
> Add support for using launch tokens

- brkt_cli/crypto/__init__.py
- brkt_cli/crypto/test_crypto.py
- brkt_cli/instance_config_args.py
Move the cert validation code in instance_config_args to a new
validate_cert() function the crypto module.  When we make the
cryptography library optional, we'll want to only call it from
brkt_cli.crypto.
> Refactor cert validation

- brkt_cli/auth.py
Expose the auth command.  We'll need it to generate API tokens when
automating image encryption.  Also update the description to say API
token.  We'll need start differentiating API token and launch token
terminology, now that we have two different token types.
> Expose the auth command

- brkt_cli/__init__.py
- brkt_cli/config/__init__.py
- brkt_cli/config/test_config.py
Remove the login, logout, and whoami commands.  We decided to use the
BRKT_API_TOKEN environment variable for auth, which works in both
interactive mode and scripting.
> Remove the login, logout, and whoami commands

- brkt_cli/esx/__init__.py
- brkt_cli/gcp/__init__.py
ESX and GCP operations require a valid token. However the token
could either be user provided as a `--token` argument or a Bracket
generated one by setting the `BRKT_API_TOKEN` argument. Hence we
should validate atleast one of them is set for these operations.
> Check for user provided and auth tokens

- brkt_cli/aws/__init__.py
- brkt_cli/aws/encrypt_ami.py
- brkt_cli/gcp/wrap_gcp_image.py
Removed all checks for verifying the Metavisor version/type as
going forward FreeBSD would be the default encryptor image used.
Also fixed log messages to refer to GCP, instead of GCE.
> Assume FreeBSD as the default encryptor image

- brkt_cli/aws/test_aws_service.py
- brkt_cli/aws/wrap_image.py
The wrap-image command (for AWS) made an assumption that the user
will have permission to launch the guest image snapshot. This is
true if the image is owned by the account where command is being
run. However in some cases, especially with the marketplace images,
the user might not have "create volume" permissions on the guest
root image snapshot. In such cases, the wrap command should:
* Launch the guest image
* Stop the guest instace
* Snapshot the guest root volume
* Terminate guest instance
* Launch the created snapshot wrapped with the Metavisor
image
> Create guest image snapshot when lacking permission

- README.md
- cryptography.md
* Move cryptography-related docs to a new cryptography.md page.
* Add docs for the new auth flow.
* Remove docs for make-key and make-token, since most users no longer
need them.
> Update README.md for 1.0.8

- README.md
- aws.md
- esx.md
- gce.md
Updated AWS, GCP and ESX documentation to reflect the current usage
and arguments. Main changes include:
* Changed GCE to GCP
* Added brkt-tag argument to all commands
* Added documentation for the `wrap` command for each of the CSPs
> Documentation updates

- brkt_cli/esx/encrypt_vmdk.py
- brkt_cli/esx/update_vmdk.py
- brkt_cli/esx/wrap_image.py
When a user specifies a Metavisor OVF, do not automatically assume
that it does not have the `.ovf` extension. Add the extension only
when it is not present.
> Normalize user specified OVF

- brkt_cli/esx/esx_service.py
- brkt_cli/esx/update_vmdk.py
- test_esx.py
During update, the old template gets replaced with the new one.
During the transition, the old one gets deleted and and the new
one is added. If something goes wrong during the addition of the
new template, the old template is lost while the new one is not
created either. So, backup the old template, then create a new one,
and finally delete the old template.
> Back up the old template till the new template is created

- brkt_cli/gcp/__init__.py
- brkt_cli/gcp/wrap_gcp_image.py
Pass the user specified instance type to the launch command instead
of always defaulting the GCP instance type for the `wrap-guest-image`
command to n1-standard-4.
> Pass the user specified instance type

- brkt_cli/aws/__init__.py
- brkt_cli/aws/aws_constants.py
- brkt_cli/aws/aws_service.py
- brkt_cli/aws/diag.py
- brkt_cli/aws/encrypt_ami.py
- brkt_cli/aws/share_logs.py
- brkt_cli/aws/test_aws.py
- brkt_cli/aws/test_aws_service.py
- brkt_cli/aws/test_encrypt_ami.py
- brkt_cli/aws/update_ami.py
- brkt_cli/aws/wrap_image.py
Move utility functions that are called from multiple places out of
encrypt_ami and into a new aws_util module.  Move constants into a new
aws_constants module.  Remove the old backward compatibility test.  It's
no longer necessary, now that we have a single CLI codebase.
> Refactor the encrypt_ami module

- brkt_cli/__init__.py
- brkt_cli/brkt_jwt/__init__.py
- brkt_cli/brkt_jwt/test_jwt.py
- brkt_cli/make_token.py
- brkt_cli/test_util.py
- brkt_cli/util.py
Split the code that handles the make-token subcommand out of the
brkt_jwt module.  This divides responsibility more clearly, and avoids
circular dependencies in JWT library callsites (e.g.
callsite->brkt_jwt->brkt_cli->brkt_jwt).
Also move the timestamp parsing functions into the util module, since
they're called from multiple places.
> Split the make-token command out of brkt_jwt

- brkt_cli/aws/__init__.py
Call _validate_ami() instead of AWSService.get_image() when validation
is disabled.  This raises ValidationError when the image doesn't exist
and the AWS API returns None.  When the user disables validation, we
still can't proceed without a valid guest image.
> Handle guest image lookup failure with --no-validate

- brkt_cli/aws/wrap_image_args.py
For the `wrap-guest-image` command, exposed the SSH Key argument.
In the absence of this argument, users may be unable to connect
to the launched instance.
> Expose SSH Key pair for wrap command

- .travis.yml
- brkt_cli/__init__.py
- brkt_cli/crypto/__init__.py
- brkt_cli/crypto/test_crypto.py
- brkt_cli/esx/esx_service.py
- brkt_cli/make_user_data/__init__.py
- requirements.txt
- setup.py
Remove the dependency on sshpubkeys, to simplify setup and avoid issues
with compiling binaries.  We were only using this library to
sanity-check the public key that is passed via the internal
--ssh-public-key option.
Replace the call to sshpubkeys with a simple string comparison that
checks the key content.
> Remove sshpubkeys dependency

- brkt_cli/__init__.py
- brkt_cli/aws/__init__.py
- brkt_cli/aws/test_encrypt_ami.py
- brkt_cli/aws/test_wrap_guest_image.py
- brkt_cli/config/__init__.py
- brkt_cli/config/test_config.py
- brkt_cli/esx/__init__.py
- brkt_cli/gcp/__init__.py
- brkt_cli/instance_config_args.py
- brkt_cli/make_token.py
- brkt_cli/make_user_data/__init__.py
- brkt_cli/test_instance_config.py
- test.py
Move the logic that handles BracketEnvironment from
instance_config_from_values() to the callsites.  We want to default the
environment to prod when encrypting and updating.  We don't want to
default it when launching with an encrypted disk, but we do when
wrapping or launching with an unencrypted disk.  And the environment can
come from either the command line or config.  It was getting hard enough
to keep track of all of these combinations that I decided to move these
decisions up to the command-line parsing code.
instance_config_from_values() now accepts a BracketEnvironment object
instead of CLIConfig.  It's the callsite's responsibility to figure out
where the environment data comes from, and whether it should be
defaulted.
Move get_yeti_service() to instance_config_args, since …
> Simplify the logic that handles BracketEnvironment

- brkt_cli/aws/aws_service.py
- brkt_cli/aws/encrypt_ami.py
- brkt_cli/aws/encrypt_ami_args.py
- brkt_cli/aws/share_logs.py
- brkt_cli/aws/test_aws_service.py
- brkt_cli/aws/test_encrypt_ami.py
- brkt_cli/aws/test_update_ami.py
- brkt_cli/aws/test_wrap_guest_image.py
- brkt_cli/aws/update_ami.py
- brkt_cli/aws/update_encrypted_ami_args.py
- brkt_cli/aws/wrap_image.py
- brkt_cli/aws/wrap_image_args.py
Use modern AWS instance types that are supported in all regions.
Default the guest instance to m4.large and use c4.xlarge for the
encryptor/updater.
> Update default AWS instance types

- brkt_cli/make_token.py
The signing key is now passed as a positional argument.  --signing-key
was deprecated in 1.0.8.
> Remove deprecated --signing-key option from make-token

- brkt_cli/esx/__init__.py
- brkt_cli/esx/esx_service.py
When using vCenter specific command, ensure that the vCenter
cluster name is specified or raise a validation error for the
same.
> Cluster name is required when using vCenter

- brkt_cli/__init__.py
- brkt_cli/aws/__init__.py
- brkt_cli/aws/encrypt_ami_args.py
- brkt_cli/aws/share_logs_args.py
- brkt_cli/aws/update_encrypted_ami_args.py
- brkt_cli/aws/wrap_image_args.py
- brkt_cli/get_public_key/__init__.py
- brkt_cli/make_key/__init__.py
- brkt_cli/make_token.py
- brkt_cli/make_user_data/__init__.py
- brkt_cli/subcommand.py
Remove the -v/--verbose option from subcommands that used it.  This
option was deprecated in the 1.0.8 release.  Users who need verbose
logging must specify --verbose at the brkt command level.
> Remove --verbose at the subcommand level

- brkt_cli/aws/__init__.py
- brkt_cli/aws/aws_service.py
- brkt_cli/aws/test_aws_service.py
- brkt_cli/aws/test_wrap_guest_image.py
- brkt_cli/aws/wrap_image.py
- brkt_cli/aws/wrap_image_args.py
Added an optional `--iam` argument which can be specified when
launching a wrapped instance. The specified IAM role is validated
before instance launch. This is useful when launching wrapped
instances to be used with Bracket Object store or other services
that depend on an instance IAM role.
> Optional IAM role for wrapped instance

- brkt_cli/instance_config_args.py
Expose --ca-cert for users who run the Bracket MCP on site.
> Expose the --ca-cert option

- brkt_cli/aws/__init__.py
- brkt_cli/aws/encrypt_ami_args.py
- brkt_cli/aws/update_encrypted_ami_args.py
Remove the old --tag option, which was replaced by --aws-tag.
> Remove deprecated --tag option

- brkt_cli/aws/__init__.py
- brkt_cli/aws/aws_args.py
- brkt_cli/aws/encrypt_ami_args.py
- brkt_cli/aws/update_encrypted_ami_args.py
- brkt_cli/aws/wrap_image_args.py
Add an aws.subnet config option for defaulting the subnet when
encrypting, updating, or wrapping an image.
> Add an aws.subnet config option

- brkt_cli/esx/encrypt_vmdk.py
- brkt_cli/esx/esx_service.py
1. Configuration of static ip requires first power on
and then power off before it can be done.
2. Add console file after static ip configuration.
3. Set a static host name.
Updater does not work yet with static IP.
> Fix configuration of static IP for encryption

- brkt_cli/make_token.py
- brkt_cli/test_util.py
- brkt_cli/util.py
Allow the expiry timestamp and not valid before timestamp to be
specified in user friendly manner of relative hour, day, week,
month or year.
> Allow make-token times specified in days, months, years

- brkt_cli/esx/encrypt_vmdk.py
- brkt_cli/esx/esx_service.py
- brkt_cli/esx/update_vmdk.py
At the end of updation/encryption, the cli sometimes hangs and does not return.
This does not happen locally.
Dumping thread state to see if a rogue thread is preventing the cli
from finishing.
> Temporary change to debug hung threads

- brkt_cli/make_user_data/__init__.py
This makes brkt-cli on par with the UI so that users can use either
the CLI or the UI to generate the userdata when launching instances.
The CLI command is especially more powerful as it allows users to
insert their own cloud-config and scripts, which is currently not
possible via the UI.
> Add `brkt-tag` argument to `make-user-data` command

- brkt_cli/esx/esx_service.py
We were seeing brkt-cli timeouts after a successful encryption.
Logs were indicating that keepalive-upload thread was preventing exit:
Thread name: MainThread Daemon: 0 IsAlive 1
Thread name: keepalive-upload Daemon: 0 IsAlive 1
Testing: Ran esx encryption successfully
> Make esx keepalive threads be daemons

- brkt_cli/aws/__init__.py
- brkt_cli/aws/aws_args.py
- brkt_cli/aws/encrypt_ami_args.py
- brkt_cli/aws/update_encrypted_ami_args.py
- brkt_cli/aws/wrap_image_args.py
- brkt_cli/esx/__init__.py
- brkt_cli/esx/encrypt_vmdk_args.py
- brkt_cli/esx/encrypt_with_esx_host_args.py
- brkt_cli/esx/esx_args.py
- brkt_cli/esx/esx_service.py
- brkt_cli/esx/update_encrypted_vmdk_args.py
- brkt_cli/esx/update_with_esx_host_args.py
- brkt_cli/esx/wrap_with_esx_host_args.py
- brkt_cli/esx/wrap_with_vcenter_args.py
- brkt_cli/mv_version.py
- brkt_cli/test_mv_version.py
Add support for determining metavisor version through published
version artifacts in AWS.
- Add mv_version module to brkt_cli
- Update esx provider to fetch OVF objects from S3 using metavisor
version
- Update esx provider to fetch amis.json using metavisor version
> Add metavisor-version argument

- brkt_cli/esx/wrap_with_esx_host_args.py
All ESX specific VMWare subcommands should refer to `esx-datastore`
and not `esx-datacenter`. A `datacenter` argument only applies for
vCenter specific commands.
> Fix argument name for `wrap-with-esx-host` command

- brkt_cli/esx/__init__.py
- brkt_cli/esx/encrypt_vmdk.py
- brkt_cli/esx/esx_service.py
- brkt_cli/esx/update_vmdk.py
- brkt_cli/esx/wrap_image.py
1. Since power-on and power-off for MV VMs is always
needed to configure static IP, move from the caller to
inside the configuration of static IP function.
Also add a comment to explain.
2. Remove the temporary hack to debug hung threads.
3. During vcenter valdation, remove the redundant
input use_esx.
> Cleanup ESX code

- brkt_cli/gcp/encrypt_gcp_image.py
- brkt_cli/gcp/gcp_service.py
- brkt_cli/gcp/update_gcp_image.py
- test_gce.py
Instances by default have an ephemeral public IP. However in cases
where we have a site-to-site VPN or the ephemeral IP is explicitly
disabled due to policy, the brkt-cli should try to use the
private IP. With this change, brkt-cli checks the encryptor status
on both the public and private IPs during encryption and updates,
much similar to AWS.
> Try to use GCP private IPs

- brkt_cli/gcp/wrap_gcp_image.py
Since the guest disk is generated based off the instance name, if
the user specified instance name is <=63 characters, we need to
ensure that the generated name for the guest_disk does not exceed
the 63 character limit enforced by GCP.
> Trim guest disk name to max supported length

- esx.md
Missed markdown rules caused document to be displayed incorrectly.
> Fix layout of ESX docs

- brkt_cli/auth.py
Update the brkt auth usage description.  Add an example of setting the
BRKT_API_TOKEN environment variable.  Use RawDescriptionHelpFormatter,
so that argparse doesn't remove newlines.
```
$ brkt auth -h
usage: brkt auth [-h] [--email ADDRESS] [--out PATH] [--password PASSWORD]
[--root-url URL]
Authenticate with the Bracket service. On success, print the API token (JSON
Web Token) that is used for making calls to Bracket REST API endpoints. You
must set the BRKT_API_TOKEN environment variable to this value, to allow other
brkt-cli commands to communicate with the Bracket service:
$ export BRKT_API_TOKEN=$(brkt auth)
-h, --help           show this help message and exit
--email ADDRESS      If not specified, show a prompt.
--out PATH           Write to a file instead of …
```
> brkt auth usage improvements

- brkt_cli/yeti.py
When the Bracket service returns an HTTP error and the message isn't
specified, generate a human-readable message that explains what went
wrong.
> Improve handling of errors from Bracket service

- brkt_cli/esx/__init__.py
- brkt_cli/esx/esx_service.py
We were not anchoring our bucket filter prefix for OVF images, which
caused us to return unofficial versions (e.g. -debug).
Also tweaked the error handling for users that are specifying both
--metavisor-version and --metavisor-ovf-image-name. The latter now
only refers to local .ovf files.
> Fix --metavisor-version to return exact version for OVF images

- brkt_cli/esx/encrypt_vmdk.py
- brkt_cli/esx/esx_service.py
1. get_obj sometimes gets exceptions when someone in
parallel is deleting other vms. Handle such exceptions.
2. Get vm in encrypt code should not fail. Retry on failure
10 times before giving up.
> Handle error in find-vm

- brkt_cli/__init__.py
- brkt_cli/aws/encrypt_ami.py
- brkt_cli/aws/update_ami.py
- brkt_cli/encryptor_service.py
Handle waiting for the encryptor instance separately from other
encryption errors.  Log an clear error when we're unable to get a
response from the encryption service.
New error output format: when an error occurs, write it at the very
bottom of the stderr output without a timestamp, to differentiate it
from logs.
Sample output:
$ ./brkt aws encrypt ami-45224425
...
16:01:25 Launching encryptor instance i-0cda6417445c92a46
16:01:36 Adding 172.31.5.227 to NO_PROXY environment variable
16:01:36 Waiting for encryption service on i-0cda6417445c92a46 (port 80
on 52.43.210.11, 172.31.5.227)
16:01:45 Unable to connect to encryptor instance.
16:01:47 Terminating instance i-039542e92360f9612
16:01:47 Terminating instance i-0cda6417445c92a46
16:01:48 Deleting snapshot snap-0d9edceff69ec8d0c …
> Improve error reporting when CLI can't talk to encryptor

- brkt_cli/auth.py
- brkt_cli/yeti.py
Before authenticating against the Bracket service, make sure that the
root URL points to the right place.
-------------
```
$ ./brkt auth --root-url http://www.google.com
http://www.google.com is not the Bracket service
$ ./brkt auth --root-url https://this.is.a.bogus.name
Unable to reach the Bracket service: HTTPSConnectionPool(host='this.is.a.bogus.name', port=443): Max retries exceeded with url: /health_check (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x109b2aa50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
```
> Validate the Bracket service URL during auth

- brkt_cli/mv_version.py
Drop this message down from info to debug.  It's an implementation
detail, and isn't interesting in the normal case.
> Log Metavisor version fetch message at debug level

- brkt_cli/esx/encrypt_vmdk.py
The variable `mv_vm_name` was being assigned after the clone VM
method. As a result, if the clone VM method hit an exception (for
e.g. due to the source VM not being found), then we were not
logging the error message properly in the except block as this
variable was unassigned.
> Initialize variable at the begining for subsequent use

- brkt_cli/esx/__init__.py
- brkt_cli/esx/encrypt_vmdk.py
- brkt_cli/esx/encrypt_vmdk_args.py
- brkt_cli/esx/encrypt_with_esx_host_args.py
- brkt_cli/esx/esx_args.py
- brkt_cli/esx/esx_service.py
Provided an optional (hidden) CDROM flag which can be used to
attach a CDROM device to the encryptor instance which is required
for PCF integration.
> Add optional CDROM configuration to encryptor VM

- brkt_cli/argutil.py
- brkt_cli/auth.py
- brkt_cli/instance_config_args.py
- brkt_cli/make_token.py
- brkt_cli/test_util.py
- brkt_cli/util.py
- brkt_cli/yeti.py
Add an --exp option to the auth command, which allows the user to
specify the lifetime of the token as a time duration.  Enable make-token
--exp when getting the launch token from the Bracket service.
Deprecate specifying token expiry in years, since the number of days in
a year can vary.
Deprecate specifying token expiry as a timestamp.  The Bracket token
service does not allow the client to specify a timestamp, so that the
server timestamp is the source of truth.  We also want expiry behavior
to be consistent for both locally-generated and server-generated tokens.
> Support launch and API token expiry

- brkt_cli/brkt_jwt/jwk.py
- brkt_cli/brkt_jwt/test_jwt.py
Sometimes the EC keypairs generated are a byte shorter.
Either x or y could be 47 bytes instead of 48 which is
mathematically valid. But when computing thumbprint,
these need to be padded with leading zeros.
Added this change.
Generated such a keypair and uploaded it to Yeti.
Made sure the KeyId computed by yeti matches the one
computed by brkt-cli
Jira: YETI-2778 #resolve
> Fix incorrect thumbprint generation for public keys

- brkt_cli/aws/aws_service.py
Contrary to what the AWS documentation states, i2.8xlarge instance
types cannot be launched as EBS optimized and doing so results
in errors.
> i2.8xlarge instance type is not EBS Optimized

- README.md
- brkt_cli/version.py
Also, update README.md to reference release 1.0.10 and use the new tag
name convention.
> Bump release version to 1.0.11pre1

- brkt_cli/aws/model.py
- brkt_cli/aws/test_aws.py
- brkt_cli/aws/test_aws_service.py
- brkt_cli/aws/test_encrypt_ami.py
- brkt_cli/aws/test_share_logs.py
- brkt_cli/aws/test_wrap_guest_image.py
Copy the boto2 classes into a new brkt_cli.aws.model module, and use
them for unit testing.  This removes dependencies on boto2 and prepares
us for the migration to boto3.
boto3 does not have statically defined models.  It generates classes and
fields from JSON schema.  When we migrate to boto3, we'll likely need to
tweak these classes to match the objects returned by the boto3 API.
> Use our own models for unit testing

- brkt_cli/aws/wrap_image.py
This change copies over any ephemeral volumes in the source guest
image that is being wrapped. Previously these volumes were
silently being dropped, making them unavailable on the wrapped
guest.
> Include the ephemeral drives from guest image

- brkt_cli/aws/aws_service.py
Don't log the reason and code when waiting for an image.  In my testing,
these always come back as None.
> Don't log reason and code when waiting for image

- brkt_cli/gcp/gcp_service.py
The GCP bucket list command returns the first 1000 items by default.
In the case where a bucket contains more than 1000 items, we do not
paginate thru' the entire list of files and as a result only
operate on the first 1000 entries. This especially causes problems
when you specify an encryptor bucket with more than 1000 files as
it incorrectly picks an older Metavisor image.
> Paginate file list in GCP buckets

- brkt_cli/mv_version.py
The logic to match a MV version to an S3 bucket element was not
paginating thru' the S3 bucket list because of which it would
only attempt to match against the first 1000 entries in the bucket.
> Paginate thru' S3 bucket elements

- brkt_cli/aws/test_aws_service.py
Don't call terminate_instance_callback twice.  Callsites expect the
argument to be the instance ID, not the instance object.
> Clean up terminate_instance_callback

- brkt_cli/aws/aws_service.py
- brkt_cli/aws/test_aws_service.py
- brkt_cli/aws/test_encrypt_ami.py
When detaching a volume during a unit test, remove it from the
instance's block device mapping.  Add a check for attempting to attach a
volume when the device name is already in use.  Update the
detach_volume() function signature, so that the instance ID is required.
Remove test_register_ami_hvm.  This test started failing because
_register_ami() assumes that the root device has already been removed
from the instance.  I verified that the existing tests cover the
non-legacy code path.
> Improve unit testing of attach/detach volume

- brkt_cli/aws/__init__.py
- brkt_cli/aws/aws_service.py
- brkt_cli/aws/boto3_device.py
- brkt_cli/aws/boto3_tag.py
- brkt_cli/aws/encrypt_ami.py
- brkt_cli/aws/model.py
- brkt_cli/aws/share_logs.py
- brkt_cli/aws/test_aws.py
- brkt_cli/aws/test_aws_service.py
- brkt_cli/aws/test_encrypt_ami.py
- brkt_cli/aws/test_share_logs.py
- brkt_cli/aws/test_update_ami.py
- brkt_cli/aws/update_ami.py
- brkt_cli/aws/wrap_image.py
Update AWS code to use boto3.  The bulk of the change is in AWSService,
but higher-level code was also affected for two reasons:
1) A bunch of field names changed
2) Embedded data structures are now dictionaries instead of objects
(2) makes application code a bit icky.  I did my best to code
around this by adding utility functions to a couple of new modules:
boto3_device and boto3_tag.
I was able to encrypt and update Ubuntu, RHEL, CentOS, and Amazon Linux
images with this change.
We still have a little bit of boto2 code in share-logs.  Mark graciously
offered to update and test the share-logs code.
> Update AWS code to use boto3

- brkt_cli/aws/aws_service.py
Filter VPCs correctly and convert to a Python list before attempting to
get the first one.  The collection returned by boto3 does not support
indexing.
> Fix get_default_vpc()

- brkt_cli/aws/aws_service.py
If an AWS key pair name was specified on the command line, pass it to
the RunInstances call.
> Fix the --key option

- brkt_cli/aws/__init__.py
- brkt_cli/aws/encrypt_ami.py
Move HVM check from encrypt_ami.encrypt() to _validate_guest_ami(), so
that we check the virtualization type for all AWS commands that operate
on a guest image.  Validate that the architecture is set to "x86_64", in
case we encounter a 32-bit HVM image.
> Improve image validation

- brkt_cli/aws/aws_service.py
- brkt_cli/aws/encrypt_ami.py
- brkt_cli/aws/model.py
- brkt_cli/aws/test_aws_service.py
- brkt_cli/aws/test_encrypt_ami.py
- brkt_cli/aws/test_update_ami.py
- brkt_cli/aws/update_ami.py
Enable ENA support on the guest instance if it's enabled on the
Metavisor instance.  Shuffle around some of the code in update_ami, to
allow us to do this earlier in the process.  If things go wrong, we'll
know sooner rather than later.  Log the "setting attribute" message at
info level for greater transparency.
> Turn on ENA support if Metavisor supports it

- brkt_cli/aws/aws_service.py
- brkt_cli/aws/model.py
- brkt_cli/aws/test_aws_service.py
With the migration to Boto3, read the console output attribute
properly from the response object. Also check if there is a valid
output before returning the same.
> Get the console output from the proper attribute

- brkt_cli/mv_version.py
When paginating thru' the S3 bucket objects to identify locate
the required metavisor version, disable credentials request
as these buckets are public. AWS credentials should not be
required when trying to download images especially for ESX.
> Disable credentials for S3 bucket pagination

- brkt_cli/aws/__init__.py
- brkt_cli/aws/encrypt_ami.py
- brkt_cli/aws/encrypt_ami_args.py
Disable the legacy code path in encrypt-ami.  This code was put in to
deal with inconsistencies in block device mappings, and problems with
unmounting the root volume from the guest.  I believe that this
workaround is no longer necessary with the latest HVM images.  I tested
the non-legacy code path with Ubuntu 12.04-16.04, CentOS 6 and 7, Amazon
Linux, RHEL 6.9-7.3, and Cloud Foundry BOSH images.  None of them
required the workaround.
This commit disables legacy mode by hard-coding the legacy variable to
False.  We can remove the legacy code altogether once we're convinced
that we didn't break backward compatibility.
> Disable legacy mode

- brkt_cli/aws/__init__.py
- brkt_cli/aws/aws_args.py
- brkt_cli/aws/encrypt_ami_args.py
- brkt_cli/aws/update_encrypted_ami_args.py
- brkt_cli/aws/wrap_image_args.py
Add an aws.security-group config key, for specifying the default
security group when launching a Metavisor instance during encryption,
update, and wrap-guest-image.
> Add config key for security group

- brkt_cli/aws/aws_service.py
- brkt_cli/aws/encrypt_ami.py
- brkt_cli/aws/update_ami.py
Turns out that the AWS API doesn't always return the enaSupport field.
When this happens, the ec2.Instance object doesn't have an ena_support
field.
Add an aws_service.has_ena_support() function, which checks if the field
is there before attempting to access it.
> Use getattr() to query the ena_support field

- brkt_cli/esx/__init__.py
- brkt_cli/esx/encrypt_vmdk.py
- brkt_cli/esx/encrypt_vmdk_args.py
- brkt_cli/esx/esx_args.py
- brkt_cli/esx/esx_service.py
This allows customers to allow addition of OVF properties
to configure static IP in the template VM or the encrypted OVF.
Primarily design for use to encrypt Ops Manager in PCF, but
is a generic implementation and can be used for any customer
which wants to use static IP.
> Add OVF properties to configure static IP

- brkt_cli/yeti.py
When validating the Bracket service endpoint, log the URL for
supportability, so that we know what the code is doing.
> Log the url when verifying Bracket service endpoint

- brkt_cli/__init__.py
- brkt_cli/argutil.py
- brkt_cli/auth.py
- brkt_cli/config/__init__.py
- brkt_cli/config/test_config.py
- brkt_cli/crypto/__init__.py
- brkt_cli/crypto/test_crypto.py
- brkt_cli/instance_config_args.py
- brkt_cli/make_token.py
- brkt_cli/yeti.py
- test.py
Add a --public-api-root-cert option to all commands that talk to the
Bracket service.  This option is used for specifying the path to the
self-signed root cert when brkt-cli talks to a Customer Managed MCP.
Also add a config environment key for this option.
Add crypto.validate_cert_path() for validating a cert that's stored on
disk.  Call this function when validating the --public-api-root-cert and
--ca-cert values.
> Add option for specifying the public API root cert

- reference_templates/brkt-cli-iam-permissions.json
The ModifyInstanceAttribute policy is required for enabling ENA
and sriovNet support on the encrypted images during the encryption
process
> Include the ModifyInstanceAttribute IAM policy

- brkt_cli/aws/__init__.py
- brkt_cli/aws/aws_service.py
- brkt_cli/aws/wrap_image.py
- brkt_cli/aws/wrap_image_args.py
After the migration to boto3, the validation method for the IAM role
as well as the instance launch method with the IAM role were failing.
Those were fixed to match the required boto3 syntax.
Also included @billybobjoeaglt change to specify a guest OS instead
of AMI ID for the wrap command.
> Fix IAM role settings with boto3

- brkt_cli/esx/esx_service.py
- brkt_cli/esx/update_vmdk.py
In case rename VM does not work, e.g. for VSAN, use the not-error-free
solution where the old template vm gets deleted, and then the new one
gets created. Thus, this can cause issues if creation of new template
fails because old one gets deleted. Committing this temporary workaround
till can find a more complete fix without rename.
> Temporary fix when rename VM does not work.

- brkt_cli/util.py
Remove the ability to specify duration in years.  This was deprecated in
a previous release because the number of days in a year is variable.
> Remove support for duration in years

- brkt_cli/util.py
Remove deprecation warnings that are logged when the user specifies
token expiry as a timestamp (as opposed to a duration).  It's convenient
to specify that a token expires at a given date and time.  When the user
specifies a timestamp, the CLI calculates the time difference and sends
it to the token service as a value in seconds.
> Remove timestamp deprecation

- brkt_cli/aws/aws_service.py
- brkt_cli/aws/encrypt_ami.py
- brkt_cli/aws/test_aws_service.py
- brkt_cli/aws/test_encrypt_ami.py
- brkt_cli/aws/update_ami.py
- brkt_cli/aws/wrap_image.py
Create tags automatically when we run an instance, create a volume, or
create an image.
Log all operations that alter the state of the AWS account.  We now log
inside AWSService, to make sure that we don't miss any callsites.
Remove extra logging from callsites.  Remove the resource type from log
messages to make them more concise.  The resource type can be inferred
from the AWS ID prefix.
Add calls to clean_up() inside AWSService methods.  This ensures that
the created resource is cleaned up if a subsequent operation (e.g.
tagging) fails or is interrupted.
Update unit tests that were affected by the new behavior.
> Improvements to tagging, AWS logging, and cleanup

- brkt_cli/aws/aws_service.py
When create_tags() is called with an empty tag set, don't call the
CreateTags API.  AWS returns a bad request error in this case.
> Don't attempt to tag when no tags were specified

- brkt_cli/aws/aws_service.py
Boto3 no longer supports `self` as a valid owner-alias (see
http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.Client.describe_images).
Instead we need to pass a new list with the owners, which allows `self` as a
valid value
> Pass owner information to images filter option correctly

- brkt_cli/aws/__init__.py
- brkt_cli/aws/aws_service.py
- brkt_cli/aws/model.py
- brkt_cli/aws/test_aws_service.py
- brkt_cli/aws/test_wrap_guest_image.py
- brkt_cli/aws/wrap_image.py
Rewrite the wrap-guest-image logic so that we modify the guest instance
instead of launching a new one.  This preserves RHEL licensing
information that's embedded in the instance and allows the user to run
yum update.
The new process is:
1) Launch the guest.
2) Stop the guest.
3) Create a Metavisor root volume based on the Metavisor AMI.
4) Move the guest root to /dev/sdf.
5) Attach the Metavisor volume at the original guest root location.
6) Start the guest.
The whole process takes about a minute.
Random related fixes:
* Add AWSService.start_instance().
* Add support for modifying user-data of an instance.  This has to be
special-cased because user-data isn't a simple string value.
* Add initialization of volume size and instance placement to
DummyAWSService, so that …
> Preserve license info when wrapping an image

- brkt_cli/aws/__init__.py
- brkt_cli/aws/aws_service.py
- brkt_cli/aws/test_aws_service.py
- brkt_cli/aws/wrap_image.py
- brkt_cli/aws/wrap_instance_args.py
Add a wrap-instance command for wrapping an AWS instance with Metavisor.
This logic is effectively the same thing as wrapping an image, except
that we don't launch an instance at the beginning of the process.
Move the bulk of the orchestration code from launch_wrapped_image() into
a new wrap_instance() function.  Add a new wrap-instance command that
calls wrap_instance() directly.
> Add aws wrap-instance command

- brkt_cli/aws/encrypt_ami.py
- brkt_cli/aws/test_encrypt_ami.py
- brkt_cli/encryptor_service.py
If we hit a timeout waiting for encryption to start, save the encryptor
console log in the same way that we do when encryption fails.  This
helps the user diagnose communication issues between the CLI and
encryptor, or between encryptor and Yeti.
Add an encryption_start_timeout argument to the encrypt() function.
This allows encryption to time out immediately in unit tests.
> Save the console log when encryption doesn't start

- brkt_cli/aws/__init__.py
- brkt_cli/mv_version.py
- brkt_cli/yeti.py
Get the Metavisor version from the Bracket service instead of using the
latest Metavisor release.  With a Customer Managed MCP that has not been
upgraded, the latest Metavisor may attempt to call service endpoints
that are not available.
> Use the version of Metavisor returned by the Bracket service

- brkt_cli/aws/aws_service.py
- brkt_cli/aws/wrap_image.py
Detaching and re-attaching volumes cause them to lose their
DeleteOnTermination property, which needs to be reset on the
running instance.
> Configure volumes for wrapped instance to be deleted on termination

- brkt_cli/aws/__init__.py
- brkt_cli/mv_version.py
- brkt_cli/yeti.py
This reverts commit 469aa9ec292e7752c6eddd68fb5d025d2b02bc22.
This commit added an auth requirement with Yeti, which caused
integration tests to start failing.  Temporarily revert this
commit until we update the tests to auth with Yeti.
> Revert "Use the version of Metavisor returned by the Bracket service"

- brkt_cli/aws/aws_service.py
Boto3 returns an image object, if the image exists, even if the user
does not access to the image. This change ensure that the user also
has access to the image before proceeding. This ensures that there are
no unexpected errors downstream.
> Validate access to image

- reference_templates/brkt-cli-iam-permissions.json
The wrap-guest-image and wrap-instance command require the additional
ModifyInstanceAttribute and StartInstances permissions to complete
successfully
> Add missing IAM permissions

- reference_templates/vpc-dual-az-with-nat.json
- reference_templates/vpc-dual-az-with-nat.py
Updated the AWS reference Cloudformation templates to use:
- NATGateway instead of NAT Instances
- A Bastion Host for SSH in to private subnet instances
- Provided a command line flag to the python script to disable the
bastion instances if the user desires
> Updates to AWS reference CloudFormation templates

- brkt_cli/aws/__init__.py
- brkt_cli/aws/encrypt_ami.py
- brkt_cli/aws/encrypt_ami_args.py
- brkt_cli/aws/test_encrypt_ami.py
The default encryptor instance type is c4.xlarge which can sometimes
be not available due to capacity issues. This argument allows a user
to override and use a different encryptor instance type to
temporarily workaround the problems. In most cases, the default
instance type would suffice (and would be used).
> Provide option to override encryptor instance type

- brkt_cli/instance_config_args.py
This changes verifies that there is a brkt.token_type attribute in
the payload of the user specified token and also ensures that this
attribute's value is set to 'Launch'.
> Verify token_type parameter in user specified token

- brkt_cli/aws/__init__.py
- brkt_cli/aws/test_aws_service.py
- brkt_cli/aws/test_wrap_guest_image.py
- brkt_cli/aws/wrap_image.py
- brkt_cli/gcp/__init__.py
Metavisor requires instances with atleast 1 vCPU and 1GB RAM. This
change validates that unsupported instances type (t1.micro and
t2.nano in AWS and f1-micro in GCP) are not allowed with the wrap
commands
> Validate instance type for wrap operations

- brkt_cli/aws/wrap_image.py
The correct attribute is `instance.instance_type` because of which the wrap image commands are failing with an AttributeError
> Fix AttributeError for wrapped images

- brkt_cli/aws/__init__.py
- brkt_cli/aws/encrypt_ami.py
- brkt_cli/encryptor_service.py
- brkt_cli/esx/__init__.py
- brkt_cli/esx/encrypt_vmdk.py
- brkt_cli/gcp/__init__.py
- brkt_cli/gcp/encrypt_gcp_image.py
- brkt_cli/gcp/update_gcp_image.py
- brkt_cli/instance_config_args.py
- brkt_cli/test_encryptor_service.py
- brkt_cli/util.py
- test_gce.py
Single-disk encryption is a way of encrypting whereby the encrypted image has the same number of disks as the unencrypted/stock image. While currently we assume there's only a root disk, the mechanism extends to images with multiple disks.
The immediate upshot is that bracketized images can be launched from the GCP or Azure console and that we therefore don't need to use the launch command in the CLI. There are less immediate advantages as well on AWS and ESX, which is why single-disk encryption is not specific to any CSP, but rather the new way to encrypt across all platforms.
Globally:
o  Introduce METAVISOR_DISK_SIZE. It holds the size of the
metavisor disk.
o  Add options --single-disk and --no-single-disk
Provide a reasonable default when neither is specified.
Add 'single-disk' to …
> YETI-3635: Add support for single-disk encryption on GCP

- brkt_cli/aws/encrypt_ami_args.py
- brkt_cli/esx/esx_args.py
- brkt_cli/gcp/encrypt_gcp_image_args.py
While single-disk encryption is enabled for GCP, for the other CSPs
the crypto_policy is being defaulted to GCM instead of XTS resulting
in the guest root volume being 2x the size.
> Default crypto policy to XTS

- brkt_cli/aws/test_encrypt_ami.py
- brkt_cli/encryptor_service.py
- brkt_cli/test_encryptor_service.py
With very large root volumes, the encryption progress, which is currently
printed as a integer might take a long time to increment and as a result
the encryption itself might timeout interpreting as a lack of progress.
This change:
- Prints the encryption progress as a float with 2 significant decimal places
- Checks the bytes_written for the encryption status instead of the progress percentage
> Better handling of encryption status for large volumes

- brkt_cli/encryptor_service.py
When doing an image update, there is no 'bytes_written' field returned
in the status. Hence check if the field exists. If not, initialize it
to 0.
> Fix traceback error during image update

- brkt_cli/aws/__init__.py
- brkt_cli/aws/aws_service.py
- brkt_cli/aws/encrypt_ami.py
- brkt_cli/aws/test_encrypt_ami.py
- brkt_cli/aws/test_update_ami.py
- brkt_cli/aws/update_ami.py
- brkt_cli/instance_config_args.py
See also 6c2b513
Additionally: don't compress the AWS user data. We don't
base64 encode it, resulting in AWS console errors. The
user data isn't so large that it needs compressing.
Jira: YETI-3635
> YETI-3635:  Support single-disk encryption for AWS

- brkt_cli/aws/__init__.py
- brkt_cli/aws/share_logs.py
- brkt_cli/aws/share_logs_args.py
- brkt_cli/aws/test_share_logs.py
Removing s3 components from share-logs. Logs file
will now download directly to local directory. This
improves the user experience, enhances security by
removing the use of public buckets, and allows for
share-logs to be used by jenkins jobs.
Testing: updated unit testing to match changes
Tested bastion usage by routing through an aws
instance
Jira: YETI-3822
> Share-logs rewrite

- brkt_cli/aws/__init__.py
- brkt_cli/instance_config_args.py
On AWS and when no encryptor AMI has been given, default to
no single-disk. This was always intended but ended up not
being the case (due to restruturing some code).
For all other CSPs, always default to single-disk from now
on.
> Change single-disk default

- brkt_cli/aws/__init__.py
Share-logs validation update
This change fixes a bug that Alexander
found when trying to enter just the <filename>
in for --destination as opposed to <path>/<filename>
This change gives the user a helpfull error message
> Share logs fix
