brkt/brkt-cli

brkt_cli/__init__.py

Clean up comments and naming, to prepare for making the source code
public:
* Remove references to NUCs
* Rename "avatar" to "encryptor"
* Clean up the description of the encryption process in the brkt_cli
module docstring.
Change-Id: I15a2448256c7509b3cdc0c4959c0a651a143d0ea

Clean up source code

---

brkt_cli/__init__.py
brkt_cli/service.py
test.py

Tag volumes attached to the snapshotter and encryptor instances.  After
instances have terminated, search for any volumes that were unexpectedly
orphaned by AWS and delete them.
Add a cleanup step for the snapshotter instance, so that it gets
terminated if something goes wrong while snapshotting the root volume.
Make the encryptor session id the same kind of shorter nonce that we use
to avoid name conflicts.
Change-Id: I39762db6c33f904a33ac8c65d75a2e58a8fc8209

Delete EBS volumes created by the copier instance

---

brkt_cli/__init__.py

Print the version when the user specifies the --version command line
argument.
Change-Id: I040924a75b041bf4d398f8af8df6a54b119f8efb

Add --version argument

---

brkt_cli/__init__.py

Eventual consistency can cause the GetVolumes API to return volumes that
were actually deleted.  Ignore this case, but log other errors.
Change-Id: Iaf0fe93772f4353089ea2990863cf35972faaa96

Ignore orphaned volume deletion errors

---

brkt_cli/__init__.py

Change-Id: Ie8ec8b5773cff9cdf3885a9a8c2dd093bbdfba11

Wait for encryptor instance to stop before snapshotting volumes

---

brkt_cli/__init__.py

Raise a new BracketError exception type instead of Exception when a
known error occurs.  Handle BracketError in main().  Log the stack trace
only if the user specified the -v option.
Change-Id: I6329157bd7dd25e2101926290e1d388a728c33a7

Handle known exceptions as errors

---

brkt_cli/__init__.py

This will point customers to the prod Bracket environment by default

Update bracket environment to prod

---

brkt_cli/__init__.py
setup.py

Change-Id: I2d742365771388bbd43ddf71d046f839c1c8a98d

Bump version to 0.9.3

---

brkt_cli/encrypt_ami.py

Copy ephemeral drive mappings from the source AMI, instead of using
hardcoded device paths.

Propagate ephemeral drive mappings

---

brkt_cli/__init__.py

Exit with an error status if the Python version is not 2.7.

Check Python version

---

brkt_cli/encrypt_ami.py
brkt_cli/encryptor_service.py
test.py

Raise an EncryptionError if there's not 1% of encryption progress in 10
minutes.

Add a timeout for encryption progress

---

brkt_cli/encrypt_ami.py

Replace unnecessary comment with one that explains why we're doing what
we're doing.

Rewrite inline comment.

---

brkt_cli/aws_service.py
brkt_cli/encrypt_ami.py
brkt_cli/encryptor_service.py
test.py

When the public and private IP are both specified for an instance, try
both until one works.

Try both public and private IPs when getting encryption status

---

brkt_cli/encrypt_ami.py
brkt_cli/update_ami.py

Allow brkt cli to validate an AMI using tags

Add identifing tags to updated AMIs

---

brkt_cli/encrypt_ami.py
test.py

Move the wait_for_instance() call out of run_guest_instance(). If
anything goes wrong while we're waiting for the guest instance to start,
we will clean up the instance in the finally block.
Remove the updater argument from run_guest_instance. I believe this is a
vestige of an earlier version of the updater code, and is no longer
used.

Always terminate guest instance

---

brkt_cli/encrypt_ami.py
brkt_cli/encryptor_service.py
test.py

TODO: add a small unit test that checks for the methods & signatures that are used by cephalopod. Test fails if they are changed in a backwards incompatible way.

Refactor to expose functions for third party use.

---

brkt_cli/__init__.py

Add descriptions to the top level brkt command and the encrypt-ami and
update-encrypted-ami subcommands.

Add command descriptions

---

brkt_cli/__init__.py

Validate the region before attempting to get the encryptor AMI.  This
avoids errors like "No AMI for us-west-3 returned" when we attempt to
look up the encryptor AMI for an invalid region.

Validate region before getting the encryptor AMI

---

brkt_cli/__init__.py

When updating an encrypted AMI, set the BrktEncryptor tag on the AMI and
any temporary AWS resources.
Move the call to _validate_guest_ami() into command_encrypt_ami().  This
call started failing for update-encrypted-ami, since we now disallow
double-encryption.

Add encryptor AMI tag when updating

---

README.md

Update README.md with the latest networking requirements for image
encryption.

Document networking requirements

---

brkt_cli/encrypt_ami.py

Read the source volume type from the right place and default the volume type to GP2.

Guest root volume should be set to GP2

---

brkt_cli/update_ami.py

Set correct volume type for GRUB and Guest Root

---

brkt_cli/__init__.py
brkt_cli/encrypt_ami.py
brkt_cli/encrypt_ami_args.py
brkt_cli/update_encrypted_ami_args.py

Get hvm encryptor amis from the hvm_amis.json file in the S3
bucket when --hvm is specified.

Add hidden --hvm flag

---

test.py

Add a unit test that verifies that we parse the --brkt-env value and
pass the values to user_data when launching the encryptor instance.
Move run_instance_callback arguments into a class, now that we have
seven of them.

Test --brkt-env

---

.travis.yml
brkt_cli/__init__.py
brkt_cli/encrypt_gce_image.py
brkt_cli/encrypt_gce_image_args.py
brkt_cli/launch_gce_image.py
brkt_cli/launch_gce_image_args.py
setup.py

Testing: encrypted a google image and verified
the encrypted guest booted

Adds option for encrypting gce images

---

brkt_cli/__init__.py

Fix validate error

---

brkt_cli/__init__.py
brkt_cli/encrypt_gce_image.py

Testing: used the brkt-env option when
encrypting an image and verified the correct
endpoints were used

Encrypt_gce_image handles brkt-env option

---

brkt_cli/__init__.py
test.py

If EC2ResponseError is raised when getting the encrypted AMI, raise a
ValidationError so that the user does not see a traceback in the command
output.  Add a unit test for this case.

When updating, raise ValidationError if the AMI does not exist

---

brkt_cli/__init__.py
brkt_cli/encrypt_gce_image.py
brkt_cli/update_encrypted_gce_image_args.py
brkt_cli/update_gce_image.py

Testing: Updated an image with and without
passing the --encrypted-image-name option
and verified the new image booted

Adds update_gce_image command

---

README.md
brkt_cli/__init__.py

Bump code version to 0.9.14pre1.
Bump latest release version in README.md to 0.9.13.

Bump version to 0.9.14pre1

---

brkt_cli/encrypt_gce_image.py

The disk to which the encrypted guest is dd'd is now
2x + 1 the size of the guest root instead of always
defaulting to 25GB
Testing: encrypted ubuntu-14.04, centos6 and rhel6
images and verified the guest booted

Encrypted guest root now resizes itself to fit guest

---

brkt_cli/aws_service.py

When verbose logging is enabled, AWSService.run_instance() now writes
user data to a temporary file.  This gives us more information when
debugging issues with launching the encryptor instance.

Write user data to temp file

---

test.py

Group all tests that parse command line options into their own test
case.  This will make it easier to unravel dependencies later, if we
decide to split test.py into multiple modules.

Refactor command line option tests

---

brkt_cli/encrypt_ami.py
test.py

If an error occurs while waiting for the root snapshot, make sure that
the snapshot is cleaned up.

Clean up the root snapshot if an error occurs

---

.travis.yml
brkt_cli/__init__.py
brkt_cli/encrypt_gce_image.py
brkt_cli/gce_service.py
brkt_cli/update_gce_image.py
setup.py
test_gce.py

Adds DummyGCEService and tests
gce image encryption and update
Testing: ran the tests and then
encrypted a gce image

Adds gce tests

---

brkt_cli/__init__.py

Gce lower case

---

brkt_cli/__init__.py
brkt_cli/encrypt_gce_image.py
brkt_cli/encrypt_gce_image_args.py
brkt_cli/gce_service.py
test_gce.py

Updated failing tests and added a new test for invalid project name

Gce image project

---

brkt_cli/encrypt_gce_image.py
brkt_cli/gce_service.py
test_gce.py

Need to pass the image_project argument in the correct order.

Yeti 826 gce launch

---

brkt_cli/launch_gce_image_args.py

Fix typo in commit

---

brkt_cli/__init__.py
brkt_cli/gce_service.py
test_gce.py

Better GCE image name validation along with added unit tests

YETI-836: Better GCE image name validation

---

.travis.yml
brkt_cli/__init__.py
brkt_cli/encrypt_gce_image.py
brkt_cli/encrypt_gce_image_args.py
brkt_cli/oauth_requests.py
brkt_cli/util.py
setup.py
test_gce.py

Testing: encrypted an image
then updated it

GCE token auth support

---

brkt_cli/gce_service.py
brkt_cli/util.py

I found wait_for_detach was failing because
retry wasn't waiting long enough. This should
fix that.

Increase retry time

---

brkt_cli/encrypt_gce_image.py

Ensures that even if things are interrupted
or exit in a weird place all the resources
created in gce will still be cleaned up
testing: encrypted and updated images
and also interrupted the encryption
processes in a few different places

Puts gce encrypt in a try finally block

---

brkt_cli/gce_service.py
brkt_cli/launch_gce_image.py

now it passes the correct value for
block_project_ssh_keys

Fix launch-gce-image command

---

brkt_cli/__init__.py
brkt_cli/update_encrypted_gce_image_args.py
brkt_cli/update_gce_image.py
test_gce.py

Add token stuff to update-gce-image

---

brkt_cli/test_util.py
test.py

test.py is now 1500 lines long and is turning into dumping ground.  Add
a separate module for util unit tests.

Add test_util.py

---

brkt_cli/aws/__init__.py
test.py

When --encryptor-ami is not specified, make sure that the specified
region is one of
* us-east-1
* us-west-1
* us-west-2
When --encryptor-ami is specified, we check against all AWS regions, in
case this is a test build of metavisor.

Improve region validation

---

brkt_cli/__init__.py

When importing a subcommand module, check ImportError.message and raise
the exception if the failed import is not the one we're expecting.
History: a subcommand import can fail for two reasons:
1) The subcommand module is missing
2) The subcommand module imports another module that's missing
We were not differentiating between these two cases, which was causing
subcommands to be ignored when a dependency was not installed.

Handle import errors inside subcommand module

---

brkt_cli/gce/encrypt_gce_image.py

Retry delete_instance during cleanup

---

brkt_cli/jwt/__init__.py
brkt_cli/test_validation.py

Also, pass the cnc value to make_jwt().  Oops.
Testing:
* python -m unittest discover
* manual

Don't allow cnc value that's less than 1

---

brkt_cli/gce/encrypt_gce_image.py
brkt_cli/gce/update_gce_image.py

If the user provides an encryptor image, do not delete it

YETI-1059: Keep user provided encryptor image

---

brkt_cli/jwt/__init__.py
brkt_cli/jwt/test_jwt.py

Add a --customer option, which adds a customer UUID to the JWT payload.

Add --customer option to make-jwk

---

README.md
brkt_cli/aws/__init__.py
brkt_cli/aws/aws_service.py
brkt_cli/aws/encrypt_ami.py
brkt_cli/aws/encrypt_ami_args.py
brkt_cli/aws/test_aws.py
brkt_cli/aws/update_ami.py
brkt_cli/aws/update_encrypted_ami_args.py
brkt_cli/encryptor_service.py
brkt_cli/test_validation.py
brkt_cli/validation.py
test.py

Default port is 8000 but allow specifying custom port. The
encryptor knows which port to use because we put it in userdata.

Add http --status-port for encryptor/updater

---

README.md
brkt_cli/aws/__init__.py
brkt_cli/aws/encrypt_ami.py
brkt_cli/aws/encrypt_ami_args.py
brkt_cli/aws/update_encrypted_ami_args.py

Now that HVM is GA, make the HVM encryptor the default one.

YETI-1103: Make HVM encryptor the default

---

brkt_cli/aws/aws_service.py
brkt_cli/aws/test_aws_service.py

Rename AWSService._retry_boto() to AWSService.retry(), so that it can be
called by AWS application code that needs custom retry logic.

Expose AWSService._retry_boto()

---

brkt_cli/__init__.py
setup.py

Update setup.py to install all of the packages under brkt_cli.  Some
subcommands didn't work because their packages weren't being installed.

Update the list of installed packages in setup.py

---

brkt_cli/get_public_key/__init__.py
brkt_cli/make_key_pair/__init__.py

These subcommands have not been officially released yet.

Hide make-key-pair and get-public-key

---

README.md

Add the command for unzipping the source.

Fix Docker instructions

---

brkt_cli/__init__.py
brkt_cli/brkt_jwt/__init__.py
brkt_cli/brkt_jwt/test_jwt.py

Validate the user-specified token.  Make sure that it's not malformed
and has all of the fields that we require.  Replace manual JWT parsing
with calls to convenience methods in brkt_jwt.

Validate the token before attempting to use it

---

brkt_cli/gce/encrypt_gce_image.py
brkt_cli/gce/gce_service.py
brkt_cli/gce/update_gce_image.py

Testing: killed encryption and verified
the console was written to a file

Dump gce console on encryptor failure

---

brkt_cli/__init__.py

Validate the JWT against /api/v1/customer/self instead of
/api/v1/jwk/{kid}.  Turns out that the JWK endpoint may not be there if
the Yeti is using a 3rd party JWK server.
Make the code more forgiving about unexpected errors.  We don't want to
interrupt the encryption process if we're unable to validate the token.
If an IOError is raised or the server returns an unexpected error
code, continue the process and let Metavisor validate the token during
encryption.

Clean up JWT validation

---

.travis.yml
brkt_cli/__init__.py
brkt_cli/aws/__init__.py
brkt_cli/aws/test_aws.py
brkt_cli/aws/update_encrypted_ami_args.py
brkt_cli/gce/encrypt_gce_image.py
brkt_cli/gce/update_gce_image.py
brkt_cli/get_public_key/__init__.py
brkt_cli/instance_config.py
brkt_cli/test_instance_config.py
brkt_cli/test_user_data.py
brkt_cli/test_util.py
test
test_gce.py

Fix errors, unused variables, and unused imports that were found by
Pyflakes.  Run Pyflakes automatically during the Travis build.  Add a
test script that runs Pyflakes and all unit tests.

Add Pyflakes to the Travis build

---

README.md

Add a networking requirement for token validation.

Update CLI networking requirements for token validation

---

brkt_cli/gce/__init__.py
brkt_cli/gce/encrypt_gce_image_args.py
brkt_cli/gce/update_encrypted_gce_image_args.py

Images, networks and JWTs are not
validated when this option is used

Adds gce no-validate option

---

brkt_cli/aws/__init__.py
brkt_cli/gce/__init__.py

Simplify the run() logic by having the method body contained within each class.

Refactor AWS and GCE subcommands

---

brkt_cli/config/__init__.py

V1 of configs don't have the 'current-environment' key

Fix config migration

---

brkt_cli/aws/encrypt_ami.py

Reverting previous change to allow tests to pass

Revert IOPS changes

---

brkt_cli/gce/__init__.py
brkt_cli/gce/encrypt_gce_image.py
brkt_cli/gce/encrypt_gce_image_args.py
brkt_cli/gce/gce_service.py
brkt_cli/gce/update_encrypted_gce_image_args.py
brkt_cli/gce/update_gce_image.py
test_gce.py

Added a subnet option to support GCE custom subnetmode networks
Display GCE HTTPErrors properly

Add subnet option for GCE custom subnetmode networks

---

brkt_cli/brkt_jwt/__init__.py

make-token          Generate a JSON Web Token for encrypting or launching
an instance

Add make-token command and help to the top level help message.

---

brkt_cli/gce/__init__.py

Launch-gce-image now prints instance name

---

brkt_cli/esx/esx_service.py

Validate the checksums of the OVF file as well as all the disks.
This will detect any interrupted downloads or corrupted files.

Validate the checksum of the downloaded OVF image

---

brkt_cli/esx/encrypt_vmdk_args.py
brkt_cli/esx/update_encrypted_vmdk_args.py

Options to generate encrypted OVF/OVA are being hidden.

Hide OVF/OVA related options

---

README.md
brkt_cli/__init__.py

Also update README.md with the 1.0.5 release.

Bump version to 1.0.6pre1

---

brkt_cli/esx/__init__.py

If the vcenter password is not provided via the environment variable,
request for it on the customer prompt.

Prompt customers for vcenter password.

---

brkt_cli/esx/esx_service.py

This change allows ESX brkt-cli to run on Windows as well.

Replace curl with requests library to upload and download ovfs.

---

brkt_cli/gce/__init__.py
brkt_cli/gce/update_encrypted_gce_image_args.py

Added better validation of the command line arguments for the
update-gce-image operand.

Better validation of command line arguments

---

aws.md
gce.md

Updates to the docs to reflect the new CLI usage conventions for AWS and GCE

Update docs to reflect new convention

---

README.md
brkt_cli/esx/__init__.py
esx.md

Added ESX usage document with examples.

Added ESX usage documentation

---

brkt_cli/esx/__init__.py
brkt_cli/esx/update_with_esx_host_args.py

- The positional VMDK argument was not required
- Changed the OVF/OVA option to use update instead of create

Fixed usage for update-with-esx-host sub-command

---

brkt_cli/gce/encrypt_gce_image.py

It turns out that the IOPS available to a VM are based on
the aggregate (or perhaps largest) drive attached to the VM.
We are bottlenecked on GCE by the speed of the dd src dest
where both src and dest are smallish (10-20G) drives.
By attaching (but not using) a large drive to the encryptor
instance results in more IOPS (typically 10x) available for
both the src and dest drives.

Improve GCE encryption speed by 10x

---

README.md
brkt_cli/__init__.py

Bump the version to 1.0.7pre1.  Bump the current release version in
README.md to 1.0.6.

Bump version to 1.0.7pre1

---

brkt_cli/aws/encrypt_ami.py
brkt_cli/aws/test_aws.py
brkt_cli/aws/test_aws_service.py
brkt_cli/aws/update_ami.py

Remove any code that deals with paravirtual images.  We no longer
support paravirtual Metavisor or guest images.

Remove PV code

---

brkt_cli/gce/encrypt_gce_image.py

For GCE, it is the `image_name` which determines the encryptor
type (NetBSD vs FreeBSD). However the `image_name` would vary
depending on how it was determined:
- User provided image file: whatever the user provided
- Published images in public buckets: the corresponding image name
- Default latest image: always returned as `latest.tar.gz`
The last case above is the most common use case where users will
simply used the `released` latest image to encrypt their GCE image.
For this case, the boot volume crypto policy would be set to 
`default` allowing the encryptor to determine the policy itself.
In all other case, the crypto policy will be set based on the image
name.

Use correct attribute to identify encryptor type

---

gce.md

Added a networking required section in the GCE page, since they
differ from other CSPs. Also added more descriptions about
optional arguments that can be used with the GCE image encryption
and update process.

Update GCE docs

---

esx.md

Updates to ESX docs to reflect the current and correct command line
options.

Updates to ESX docs

---

.travis.yml
brkt_cli/__init__.py
brkt_cli/esx/esx_service.py
brkt_cli/make_user_data/__init__.py
requirements.txt
setup.py

Added a method to validate SSH public keys passed with certain CLI
command (VMWare encrypt/update and make-user-data).

Validate SSH Public keys

---

README.md

Fixed the links to the ESX docs.

Fix doc link for ESX docs

---

brkt_cli/esx/encrypt_vmdk.py
brkt_cli/esx/esx_service.py

Set the MV name so that it can be cleaned up
on encryption error.

VM not cleaned up on encryption error

---

brkt_cli/config/__init__.py

Remove ConfigSubcommand._write_config() and move the code into
CLIConfig.save_config().  Before this change, we created ~/.brkt only
when calling ConfigSubcommand.  Callsites that called
CLIConfig.save_config() would fail when ~/.brkt didn't exist.

Consolidate the code that saves the config file

---

brkt_cli/__init__.py
brkt_cli/config/__init__.py
brkt_cli/gcp/__init__.py
brkt_cli/gcp/encrypt_gcp_image.py
brkt_cli/gcp/encrypt_gcp_image_args.py
brkt_cli/gcp/gcp_service.py
brkt_cli/gcp/launch_gcp_image.py
brkt_cli/gcp/launch_gcp_image_args.py
brkt_cli/gcp/share_logs_gcp_args.py
brkt_cli/gcp/update_encrypted_gcp_image_args.py
brkt_cli/gcp/update_gcp_image.py
brkt_cli/test_instance_config.py
setup.py
test_gce.py

Update the code and command line usage to use the term "GCP" instead of
"GCE".

Rename GCE to GCP

---

brkt_cli/esx/esx_service.py

Indicate to the lease thread both using lease state
and a global variable to kill itself.

Kill the lease thread using global variable

---

brkt_cli/esx/__init__.py
brkt_cli/esx/encrypt_vmdk.py
brkt_cli/esx/encrypt_vmdk_args.py
brkt_cli/esx/esx_service.py
brkt_cli/esx/update_encrypted_vmdk_args.py
brkt_cli/esx/update_vmdk.py
brkt_cli/esx/wrap_image.py
brkt_cli/esx/wrap_with_vcenter_args.py
brkt_cli/util.py

Use vCenter customization APIs to configure static IP address,
default router, subnet mask, DNS domain and DNS servers.

Allow configuration of static IP on the encryptor VM

---

brkt_cli/auth.py
brkt_cli/make_token.py

Update command line usage for the auth and make-token commands.
Describe the difference between API tokens and launch tokens.  Document
the BRKT_API_TOKEN environment variable.

Update auth and make-token usage

---

brkt_cli/esx/encrypt_vmdk_args.py
brkt_cli/esx/encrypt_with_esx_host_args.py
brkt_cli/esx/esx_args.py
brkt_cli/esx/rescue_metavisor_args.py
brkt_cli/esx/update_encrypted_vmdk_args.py
brkt_cli/esx/update_with_esx_host_args.py
brkt_cli/esx/wrap_with_esx_host_args.py
brkt_cli/esx/wrap_with_vcenter_args.py

Consolidated common ESX command line arguments across the various
ESX commands. Help texts were also modified to reflect the actual
usage/purpose of the argument.

Consolidate common ESX command line arguments

---

brkt_cli/esx/wrap_image.py

1. Fix static IP configuration for wrap script.
2. Fix VM reconfiguration for wrap script.

Fix static ip configuration for wrap script

---

brkt_cli/esx/encrypt_vmdk.py
brkt_cli/esx/esx_service.py
brkt_cli/esx/update_vmdk.py
brkt_cli/esx/wrap_image.py
test_esx.py

This allow multiple encryption jobs to be run in parallel
on the same guest vmdk.

Clone the guest disk before encryption and then delete it

---

brkt_cli/aws/aws_service.py

Remove unused AWSService.connect_as() method.

Remove AWSService.connect_as()

---

brkt_cli/aws/__init__.py
brkt_cli/aws/encrypt_ami_args.py

Added stock images to the CLI (Ubuntu and CentOS) and fixed uncaught error when the AMI is from the AWS marketplace

Ubuntu and CentOS keywords

---

brkt_cli/aws/update_ami.py

Simplify the update_ami code and remove a bunch of (hopefully)
unnecessary logic.
Hardcode the Metavisor and guest root device names, instead of reading
them from the block device mappings.  We don't expect these to change
any time soon.
Consolidate the hacks that preserve volume settings, such as volume type
and IOPS, so that they don't obfuscate the rest of the code.

Simplify the update_ami code

---

brkt_cli/esx/esx_service.py

1. Network needs to be set correctly before launching OVF.
2. Dump import spec error and warning in case of error.

Add network name to OVF spec before launching OVF

---

brkt_cli/aws/encrypt_ami.py

Remove the ami_info dictionary, which contained a bunch of properties
about the encrypted image.  It's no longer being used.  Update
_register_ami() to return the Image object and fix callsites.

Remove the ami_info data structure

---

brkt_cli/esx/esx_args.py
brkt_cli/esx/esx_service.py

Add support for port-groups and virtual-port-groups.
Expose option nic-type to customers to allow them to choose
the network type they want to configure.

Add support for port-groups

---

brkt_cli/aws/wrap_image.py

The wrap command should cleanup AWS resources when user interrupts
the operation with a ^C.

Cleanup AWS resources when interrupted

---

brkt_cli/esx/__init__.py
brkt_cli/esx/assign_static_ip_args.py
brkt_cli/esx/esx_service.py

Assume that the VM has been created via encryptor which was
assigned a static IP. Thus, it has the old IP retained from
the encryption time.

Add command to configure static-ip on VM

---

.travis.yml
requirements.txt
setup.py

Remove boto2 from requirements, now that the code no longer depends on
it.

Remove boto2

---

aws.md

Added information on encrypting stock images on AWS as well as the
corresponding new argument (`--stock-image-version`)

Documentation updates

---

README.md
brkt_cli/version.py

Bump version to 1.0.12pre1.  Update README to reference the 1.0.11
release.

Bump version to 1.0.12pre1

---

brkt_cli/aws/aws_service.py
brkt_cli/aws/encrypt_ami.py
brkt_cli/aws/wrap_image.py

Enable sriovNetSupport and ENA for a wrapped image or instance, if
necessary

Enable sriovNet and ENA for wrapped image/instance

---

aws.md

Added docs with help and usage information on the wrap-instance
command

Update docs with wrap-instance command

---

brkt_cli/aws/update_ami.py

AMZN Linux images use /dev/xvda as the default root device whereas
the CLI updater assumes the root device to be always present at
/dev/sda1. As a result, the update image was failing as it was not
reading the volume information from the instance block device mappings
using the correct attach point for AMZN Linux images.

Update image failing for AMZN Linux

---

README.md
brkt_cli/version.py

Bump version to 1.0.14pre1

---

brkt_cli/gcp/update_gcp_image.py
test_gce.py

The bug was introduced when the tests were fixed in my previous change.

Fix GCP update

---

brkt_cli/esx/__init__.py
brkt_cli/esx/encrypt_vmdk.py
brkt_cli/esx/esx_service.py
brkt_cli/esx/update_vmdk.py
brkt_cli/instance_config_args.py
test
test-travis
test_esx.py

See also 6c2b513b57e42659d5c3e3bb198ab7aa1ee2cda7
Jira: YETI-3635

YETI-3635: Support single-disk encryption for vmware

---

README.md

Bump the reference to latest released CLI version to 1.0.15.

Bump released version in README
